(function(root){'use strict';
 const P=root.PikolPremium,E=P.esc,I=P.icon,q=s=>document.querySelector(s);let last=null,options=null;
 function state(m){try{return JSON.parse(m.presentation_state||'{}');}catch(_){return {};}}
 function player(p){return `<div class="sc-player">${P.avatar(p,true)}<strong>${E(p.display_name||p.full_name||'Player')}</strong><small>${p.rating!=null?'★ '+Number(p.rating).toFixed(1)+' · ':''}${E(p.player_division||'')}</small></div>`;}
 function render(d,opt){last=d;options=opt;const m=d.match,s=state(m),t=d.tournament||{},v=d.division||{};
   ['a','b'].forEach(side=>{const team=m['team_'+side]||{name:m['team_'+side+'_name']||'TBA',members:[]};q('#team-'+side).textContent=team.name;q('#seed-'+side).textContent=team.seed?'#'+team.seed+' SEED':'OFFICIAL TEAM';q('#players-'+side).innerHTML=team.members.length?team.members.map(player).join(''):player({display_name:team.name});const panel=q('#competitor-'+side);panel.querySelector('.sc-team-bg')?.remove();const url=P.asset(team.banner_url);if(url)panel.insertAdjacentHTML('afterbegin',`<img class="sc-team-bg" src="${E(url)}" alt="" data-tp-avatar>`);q('#serve-'+side).classList.toggle('hidden',s.serving_side!==side);q('#minus-'+side).disabled=!opt.canScore||Number(m['score_'+side])===0;q('#control-'+side+'-label').textContent=team.name;q('#set-serve-'+side).textContent=team.name;q('#set-serve-'+side).disabled=!opt.canControl;q('#set-serve-'+side).setAttribute('aria-pressed',String(s.serving_side===side));});
   document.body.classList.toggle('sc-swapped',!!s.swapped);q('#sc-switch').disabled=!opt.canControl;q('#sc-timeout').disabled=!opt.canScore;q('#sc-timeout').innerHTML='Ⅱ<span>'+(s.timeout?'End Timeout':'Timeout')+'</span>';
   q('#sc-game-state').textContent=s.timeout?'TIMEOUT':m.status==='completed'?'FINAL RESULT':'OFFICIAL MATCH SCORE';q('#sc-serving').textContent=s.serving_side?'● SERVE · '+(m['team_'+s.serving_side]?.name||m['team_'+s.serving_side+'_name']||'Side '+s.serving_side.toUpperCase()):'Serving side not set';
   q('#sc-progress').textContent=m.status==='live'?(s.timeout?'Timeout in progress':'Match in progress'):P.label(m.status);q('#scorer-identity').innerHTML=opt.me?P.avatar(opt.me)+`<span>${E(opt.me.full_name)}<small>${E(P.label(opt.me.role))}</small></span>`:'';
   q('#sc-write-state').textContent=opt.connected?(opt.canControl?'Changes saved to server':'Read only · No scoring control'):'Connection lost · Controls disabled';
   q('#sc-info').innerHTML=`<div class="sc-info-row">${I('trophy')}<span><strong>${E(m.tournament_name||t.name)}</strong><small>${E(t.venue||'')}</small></span></div><div class="sc-info-row">${I('calendar')}<span><strong>${P.date(t.tournament_date||m.scheduled_date)}</strong><small>${m.scheduled_time?P.time(m.scheduled_time):'Time to be assigned'}</small></span></div><div class="sc-info-row">${I('pin')}<span><strong>${E(m.court_name||'Court TBA')}</strong><small>${E(t.venue||'Tournament venue')}</small></span></div><div class="sc-info-row">${I('users')}<span><strong>${E(m.division_name||v.name)}</strong><small>${E(P.label(m.round))} · ${E(P.label(v.match_type))}</small></span></div><div class="sc-info-row">${I('bracket')}<span><strong>${E(P.label(v.competition_format))}</strong><small>Official match score</small></span></div><section class="sc-official"><h3>Officials</h3>${P.memberRow({full_name:m.scorer_name||opt.me?.full_name||'Scorer not assigned',player_division:m.scorer_name?'Assigned scorer':opt.me?'Current operator':''})}</section>`;
   q('#sc-court-queue').innerHTML=`<h3>Next on ${E(m.court_name||'this court')}</h3>${(d.queue||[]).slice(0,4).map(n=>`<article class="sc-next-match"><div class="tp-row"><span>${P.badge(n.status)}</span><small>${P.time(n.scheduled_time)}</small></div><div class="tp-versus-row"><div>${P.people(n.team_a)}<strong>${E(n.team_a?.name||'TBA')}</strong></div><b>vs</b><div>${P.people(n.team_b)}<strong>${E(n.team_b?.name||'TBA')}</strong></div></div><small>${E(n.division_name)} · ${E(P.label(n.round))}</small></article>`).join('')||'<p class="tp-muted">No upcoming matches assigned to this court.</p>'}`;
   q('#history').innerHTML=(d.history||[]).map(h=>`<div class="hist"><time>${new Date(h.created_at).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time><span class="sc-event-icon">${h.action==='score'?I('ball'):h.action==='complete'?I('check'):I('clock')}</span><span><strong>${E(P.label(h.action))}</strong><small>${E(h.details||'')} · ${E(P.label(h.actor_role))}</small></span><b>${Number(h.score_a||0)} - ${Number(h.score_b||0)}</b></div>`).join('')||'<div class="tp-empty">No scoring events yet. Start the match to begin the audit timeline.</div>';
   q('#sc-preview-score').innerHTML=`<strong>${E(m.team_a?.name||m.team_a_name||'TBA')}</strong><b>${Number(m.score_a||0)} <span>●</span> ${Number(m.score_b||0)}</b><strong>${E(m.team_b?.name||m.team_b_name||'TBA')}</strong>`;
   elapsed();
 }
 function elapsed(){if(!last)return;const m=last.match,end=m.completed_at?Date.parse(m.completed_at):Date.now(),seconds=m.started_at?Math.max(0,Math.floor((end-Date.parse(m.started_at))/1000)):0;q('#sc-elapsed').textContent='Elapsed '+Math.floor(seconds/60).toString().padStart(2,'0')+':'+(seconds%60).toString().padStart(2,'0')+' · includes pauses';}
 setInterval(()=>{if(!document.hidden)elapsed();},1000);
 function bind(c){q('#sc-brand').addEventListener('error',function(){if(!this.dataset.failed){this.dataset.failed='1';this.src='icons/icon-192.png';}});fetch((root.PIKOL_API_BASE||'')+'/api/branding').then(r=>r.json()).then(b=>{const logo=P.asset(b.app_logo_url||b.logo_url);if(logo)q('#sc-brand').src=logo;q('#sc-brand').alt=b.facility_name||'PIKOL';}).catch(()=>{});const url=new URL('scoring.html',location.href);url.search='?match='+encodeURIComponent(c.matchId)+'&display=1';q('#sc-public-link').href=url.href;q('#sc-share').onclick=async()=>{try{await navigator.clipboard.writeText(url.href);c.toast('Public scoreboard link copied.');}catch(_){prompt('Copy public scoreboard link',url.href);}};q('#sc-fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(_){c.toast('Fullscreen is not supported on this device.');}};
 ['info','queue'].forEach(name=>q('#sc-'+name+'-tab').onclick=()=>{document.querySelector('.score-side').classList.toggle('sc-queue-only',name==='queue');['info','queue'].forEach(v=>{q('#sc-'+v+'-tab').classList.toggle('is-active',name===v);q('#sc-'+v+'-tab').setAttribute('aria-pressed',String(name===v));});});
 }
 function assigned(rows,today){
   today=today||new Date().toLocaleDateString('en-CA');
   const groups=[['live','Live now'],['today','Today'],['upcoming','Upcoming'],['completed','Completed']],buckets={live:[],today:[],upcoming:[],completed:[]};
   rows.forEach(m=>buckets[m.status==='completed'?'completed':m.status==='live'?'live':m.scheduled_date&&m.scheduled_date<=today?'today':'upcoming'].push(m));
   q('#assigned-summary').innerHTML=groups.map(([key,title])=>`<div><strong>${buckets[key].length}</strong><span>${title}</span></div>`).join('');
   q('#assigned-list').innerHTML=rows.length?groups.filter(([key])=>buckets[key].length).map(([key,title])=>`<section class="sc-assigned-group"><h3>${title} <span>${buckets[key].length}</span></h3><div class="sc-assigned-grid">${buckets[key].map(m=>`<article class="sc-assigned-card"><header><span>${E(m.tournament_name)}</span>${P.badge(m.status)}</header><h4>${E(m.division_name)}</h4><p class="sc-round">${E(P.label(m.round))} · Match ${m.match_number||m.id}</p><div class="sc-assigned-teams">${['a','b'].map(side=>{const team=m['team_'+side];return `<div>${team?.banner_url?P.picture(team.banner_url,team.name+' banner','sc-assigned-banner'):''}${P.people(team)}<strong>${E(team?.name||m['team_'+side+'_name']||'Awaiting qualifier')}</strong><small>${E((team?.members||[]).map(p=>p.display_name||p.full_name).join(' / '))}</small></div>`;}).join('<span class="sc-vs">vs</span>')}</div><p class="sc-assigned-meta">${P.icon('calendar')}${m.scheduled_date?P.date(m.scheduled_date):'Date TBA'} · ${m.scheduled_time?P.time(m.scheduled_time):'Time TBA'}<br>${P.icon('pin')}${E(m.court_name||'Court TBA')}</p><button class="btn btn-primary" data-open-match="${m.id}">${m.status==='completed'?'View Result':'Open Scoring'} →</button></article>`).join('')}</div></section>`).join(''):'<div class="sc-assigned-empty"><h3>No assigned matches yet</h3><p>Your matches appear here automatically after the administrator runs Auto Schedule.</p></div>';
 }
 function installApp(){
   let pending=null;const button=q('#sc-install'),help=q('#sc-install-help');
   const installed=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
   function sync(){button.hidden=installed();}
   window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();pending=e;sync();});
   window.addEventListener('appinstalled',()=>{pending=null;button.hidden=true;help.hidden=true;});
   button.onclick=async()=>{if(pending){await pending.prompt();await pending.userChoice;pending=null;}else{help.hidden=!help.hidden;help.textContent=(/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1))?'In Safari, open Share → Add to Home Screen to install PIKOL Scorer. On iPad, use the Share button in the toolbar.':'Use your browser’s Install App or Add to Home Screen command. HTTPS and a supported browser are required.';}};
   window.addEventListener('pageshow',sync);sync();
   if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js?v=74-system-audit',{scope:'./',updateViaCache:'none'}).then(reg=>reg.update()).catch(()=>{}));
 }
 window.addEventListener('DOMContentLoaded',installApp);
 root.PikolScoring={render,bind,assigned};
})(window);
