/* PIKOL tournament presentation. All operational actions use the existing application/API. */
(function(root){
  'use strict';
  const E=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const L=v=>String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
  const q=(s,h=document)=>h.querySelector(s);
  const qa=(s,h=document)=>Array.from(h.querySelectorAll(s));
  const fallback='assets/booking/hero-court.jpg';
  const paths={trophy:'M7 3h10v6a5 5 0 0 1-10 0V3Zm0 2H3v3a4 4 0 0 0 4 4m10-7h4v3a4 4 0 0 1-4 4m-5 2v6m-4 1h8',calendar:'M8 2v4m8-4v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2Zm2 10h3v3H7Z',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-3.87M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm8 0a4 4 0 0 1 0 8',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Zm-5 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',clock:'M12 8v5l3 2m7-3a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',grid:'M3 3h7v7H3Zm11 0h7v7h-7ZM3 14h7v7H3Zm11 0h7v7h-7Z',home:'m3 10 9-8 9 8v11h-6v-7H9v7H3V10Z',live:'M9 5a8 8 0 0 0 0 14m6-14a8 8 0 0 1 0 14M7 2a12 12 0 0 0 0 20M17 2a12 12 0 0 1 0 20M12 10v4',bracket:'M3 3h5v5H3Zm0 13h5v5H3Zm13-7h5v5h-5ZM8 5h4v14H8m4-7h4',search:'M16 16l6 6M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z',arrow:'M4 12h16m-6-6 6 6-6 6',check:'m4 12 5 5L20 6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',bell:'M18 8a6 6 0 0 0-12 0v7l-2 3h16l-2-3V8Zm-9 13h6',money:'M3 5h18v14H3Zm9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z',chart:'M3 13h4v8H3Zm7-7h4v15h-4Zm7-4h4v19h-4Z',ball:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0ZM8 7h.01M15 6h.01M6 13h.01M12 12h.01M18 13h.01M9 18h.01M16 18h.01'};
  const icon=(name,cls='')=>`<svg class="tp-icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.trophy}"/></svg>`;
  let ctx=null,epoch=0,detail=null,tab='overview',divisionId=null,list=[],myMatches=[],adminCtx=null;
  const asset=v=>{const s=String(v||'');if(!s)return '';if(/^https?:\/\//i.test(s))return s;if(s.startsWith('/branding/'))return (root.PIKOL_API_BASE||'')+s;if(/^assets\//.test(s))return s;return '';};
  const initials=name=>String(name||'?').trim().split(/\s+/).slice(0,2).map(s=>s[0]).join('').toUpperCase();
  const hue=name=>Array.from(String(name||'')).reduce((a,c)=>a+c.charCodeAt(0)*11,0)%360;
  const date=v=>v?new Date(v.slice(0,10)+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Date to be announced';
  const time=v=>v?new Date('2000-01-01T'+v).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'}):'Time TBA';
  const money=n=>ctx?ctx.money(Number(n||0)):adminCtx?adminCtx.money(Number(n||0)):new Intl.NumberFormat(undefined,{style:'currency',currency:'PHP'}).format(Number(n||0));
  const button=(text,attrs='',kind='outline')=>`<button type="button" class="tp-btn tp-${kind}" ${attrs}>${text}</button>`;
  const empty=(title,msg='')=>`<div class="tp-empty"><span>${icon('trophy')}</span><strong>${E(title)}</strong><p>${E(msg)}</p></div>`;
  const badge=(status,text)=>`<span class="tp-badge tp-status-${E(status)}">${['live','ongoing'].includes(status)?'<i></i>':''}${E(text||L(status))}</span>`;
  const status=t=>t.registration_open?badge('open','Registration open'):badge(t.status,['published','registration_open'].includes(t.status)?'Registration closed':null);
  function avatar(p={},large=false){const name=p.full_name||p.display_name||p.name||'Player',url=asset(p.profile_thumbnail_url||(root.PikolVenueUI?root.PikolVenueUI.thumb(p.profile_photo_url):p.profile_photo_url));return `<span class="tp-avatar${large?' tp-avatar-lg':''}" style="--avatar-hue:${hue(name)}" title="${E(name)}"><span>${E(initials(name))}</span>${url?`<img src="${E(url)}" alt="${E(name)}" loading="lazy" decoding="async" data-tp-avatar>`:''}</span>`;}
  const people=team=>`<span class="tp-avatar-stack">${(team?.members||[]).slice(0,2).map(p=>avatar(p)).join('')||avatar({name:team?.name||'TBA'})}</span>`;
  const picture=(url,alt='',cls='')=>`<img class="tp-photo ${cls}" src="${E(asset(url)||fallback)}" alt="${E(alt||'Pickleball venue promotional illustration')}" loading="lazy" decoding="async" data-tp-image>`;
  const banner=(team)=>`<div class="tp-team-banner" style="--team-hue:${hue(team.name)}">${asset(team.banner_url)?picture(root.PikolVenueUI?root.PikolVenueUI.thumb(team.banner_url):team.banner_url,team.name+' team banner'):''}<span class="tp-team-monogram">${E(initials(team.name))}</span>${team.seed?`<span class="tp-seed">#${E(team.seed)} SEED</span>`:''}</div>`;
  const rating=p=>p.rating!=null?`★ ${Number(p.rating).toFixed(1)} · `:'';
  const memberRow=p=>`<div class="tp-person">${avatar(p)}<span><strong>${E(p.full_name||p.display_name||'Player')}</strong><small>${rating(p)}${E(p.player_division||'Registered participant')}</small></span></div>`;
  const dateRange=t=>date(t.tournament_date)+(t.end_date&&t.end_date!==t.tournament_date?' – '+date(t.end_date):'');
  document.addEventListener('error',e=>{if(e.target.matches&&e.target.matches('[data-tp-avatar]'))e.target.remove();else if(e.target.matches&&e.target.matches('[data-tp-image]')){if(e.target.dataset.failed)e.target.remove();else{e.target.dataset.failed='1';e.target.src=e.target.closest('.tp-brand')?'icons/icon-192.png':fallback;}}},true);

  const allMatches=d=>d.divisions.flatMap(v=>(v.matches||[]).map(m=>({...m,tournament_id:d.tournament.id,division_name:v.name,division_id:v.id,competition_format:v.competition_format,match_duration_minutes:v.match_duration_minutes})));
  function setup(c){ctx=c;const sheet=q('#tab-tournaments');sheet.classList.add('tp-page');if(sheet.dataset.tpBound)return;sheet.dataset.tpBound='1';sheet.addEventListener('click',handlePlayerClick);sheet.addEventListener('change',handleChange);bindCards(sheet);}
  function bindCards(host){if(host.dataset.cardsBound)return;host.dataset.cardsBound='1';host.addEventListener('keydown',e=>{if(e.defaultPrevented)return;const card=e.target.closest('[data-card-nav]');if(card&&e.target===card&&['Enter',' '].includes(e.key)){e.preventDefault();card.click();}});}
  const cta=t=>t.registration_open?button('Register Now',`data-tp-register="${t.id}"`,'gold'):'';
  const facts=t=>`<p class="tp-event-meta">${E(date(t.tournament_date))}${t.end_date&&t.end_date!==t.tournament_date?' – '+E(date(t.end_date)):''} · ${E(t.venue||t.court_name||'Venue TBA')}</p>`;
  const stats=(t,d)=>`<div class="tp-chips"><span>${d?d.divisions.length:Number(t.division_count||0)} divisions</span><span>${d?d.divisions.reduce((n,v)=>n+(v.teams||[]).length,0):Number(t.team_count||0)} teams</span><span>${money(d?.prize_pool??t.prize_pool)} prize pool</span></div>`;
  function eventCard(t){return `<article class="tp-event-card" role="link" tabindex="0" data-card-nav data-tp-open="${t.id}" aria-label="Open ${E(t.name)}"><div class="tp-card-image">${picture(t.poster_url,t.name)}${status(t)}</div><div class="tp-card-body"><h3>${E(t.name)}</h3>${facts(t)}${stats(t)}${cta(t)}</div></article>`;}
  function matchCard(m){return `<article class="tp-match-card" role="button" tabindex="0" data-card-nav data-tp-match="${m.id}" aria-label="Match ${m.match_number||m.id}: ${E(m.team_a?.name||m.team_a_name||'TBA')} versus ${E(m.team_b?.name||m.team_b_name||'TBA')}"><div class="tp-row">${badge(m.status)}<small>${E(m.scheduled_date?date(m.scheduled_date):'Date TBA')} ${m.scheduled_time?time(m.scheduled_time):''}</small></div><div class="tp-versus-row"><strong>${E(m.team_a?.name||m.team_a_name||'TBA')}</strong><b>${['live','completed'].includes(m.status)?`${m.score_a} : ${m.score_b}`:'vs'}</b><strong>${E(m.team_b?.name||m.team_b_name||'TBA')}</strong></div><p class="tp-muted">${E(m.division_name||'')} · ${E(L(m.round))} · ${E(m.court_name||'Court TBA')}</p>${m.status==='live'?`<a class="tp-btn tp-outline" href="scoring.html?match=${m.id}&display=1">Live Score</a>`:m.scheduled_date&&m.scheduled_time&&m.status!=='completed'?button('Add to calendar',`data-tp-calendar="${m.id}"`):''}</article>`;}
  async function load(c){setup(c);const request=++epoch;detail=null;q('#tn-detail-view').classList.add('hidden');q('#tn-list-view').classList.remove('hidden');q('#tn-list-view').innerHTML=empty('Loading tournaments…');try{const [rows,matches]=await Promise.all([c.api('/api/tournaments'),c.user()?c.api('/api/my/matches'):Promise.resolve([])]);if(request!==epoch)return;list=rows;myMatches=matches;renderDiscovery();}catch(error){q('#tn-list-view').innerHTML=empty('Could not load tournaments',error.message)+button('Retry','data-tp-discovery');}}
  function renderDiscovery(){q('#tn-list-view').innerHTML=`<label class="tp-search">${icon('search')}<input type="search" id="tp-search" placeholder="Search tournaments or venues" aria-label="Search tournaments"></label><section class="tp-discovery-events"><div class="tp-event-grid">${list.map(eventCard).join('')||empty('No published tournaments yet','Check back for upcoming competitions.')}</div></section><section class="tp-surface" id="tp-my-matches"><h2>My Matches</h2><div class="tp-match-grid">${myMatches.filter(m=>m.status!=='cancelled').slice(0,6).map(matchCard).join('')||empty('Your next match starts here',ctx.user()?'Approved entries appear here after the draw is generated.':'Sign in to see your matches.')}</div></section>`;q('#tp-search').oninput=e=>{const term=e.target.value.toLowerCase();qa('.tp-event-card').forEach(el=>el.hidden=!el.textContent.toLowerCase().includes(term));};}
  async function open(id,c,requestedTab,silent){setup(c);const request=++epoch;if(detail?.tournament.id!==Number(id)){tab='overview';divisionId=null;}if(requestedTab)tab=({'teams':'participants','players':'participants','divisions':'overview','courts':'schedule','rules':'overview'})[requestedTab]||requestedTab;q('#tn-list-view').classList.add('hidden');q('#tn-detail-view').classList.remove('hidden');if(!silent)q('#tn-detail-view').innerHTML=empty('Loading tournament…');try{const d=await c.api('/api/tournaments/'+id);if(request!==epoch)return;if(silent&&JSON.stringify(d)===JSON.stringify(detail))return;detail=d;if(!d.divisions.some(v=>v.id===Number(divisionId)))divisionId=d.divisions[0]?.id;renderDetail();}catch(error){q('#tn-detail-view').innerHTML=empty('Unable to load tournament',error.message)+button('All tournaments','data-tp-discovery');}}
  function selectedDivision(d,id){return d.divisions.find(v=>String(v.id)===String(id))||d.divisions[0];}
  function teamCard(t,d,admin=false){const own=admin||(ctx?.user()&&(t.members||[]).some(m=>m.user_id===ctx.user().id));return `<article class="tp-team-card">${banner(t)}<div><h3>${E(t.name)}</h3><p>${E(d.name)} · ${E(L(d.match_type))}${t.seed?' · Seed '+t.seed:''}</p>${(t.members||[]).map(memberRow).join('')}${own?`<div class="tp-actions">${button('Edit identity',`data-tp-team-edit="${t.id}"`)}<label class="tp-btn tp-outline">Upload banner<input type="file" accept="image/jpeg,image/png,image/webp" data-tp-banner="${t.id}" class="tp-file-input" aria-label="Upload team banner"></label></div>`:''}</div></article>`;}
  const tabs=['overview','bracket','schedule','participants','standings'];
  function workspace(d,id,active,admin=false){const v=selectedDivision(d,id);return `<section class="tp-workspace" data-workspace-division="${v?.id||''}"><div class="tp-selector"><label for="tp-division-${admin?'admin':'player'}"><strong>${admin?'Manage':'Follow'} Division</strong><select class="select" id="tp-division-${admin?'admin':'player'}" data-tp-select-division ${v?'':'disabled'}>${d.divisions.map(x=>`<option value="${x.id}" ${x.id===v?.id?'selected':''}>${E(x.name)} · ${E(L(x.match_type))}</option>`).join('')||'<option>No divisions yet</option>'}</select></label><div class="tp-selector-meta">${v?divisionMeta(v):'Add a division to begin.'}</div></div>${v?`<nav class="tp-workspace-tabs" role="tablist" aria-label="Selected division workspace">${tabs.map(key=>`<button type="button" role="tab" id="tp-${admin?'admin':'player'}-${key}" data-tp-tab="${key}" aria-selected="${key===active}" aria-controls="tp-${admin?'admin':'player'}-panel" tabindex="${key===active?0:-1}">${L(key)}</button>`).join('')}</nav>${admin?toolbar(v):''}<div class="tp-surface tp-workspace-panel" role="tabpanel" id="tp-${admin?'admin':'player'}-panel" aria-labelledby="tp-${admin?'admin':'player'}-${active}">${workspaceContent(d,v,active,admin)}</div>`:empty('No divisions yet','The organiser will publish the competition categories here.')}</section>`;}
  function divisionMeta(v){const matches=v.matches||[],done=matches.filter(m=>m.status==='completed'||m.status==='bye').length;return `${v.teams?.length||0} teams · ${matches.length} matches · ${matches.length?Math.round(done/matches.length*100):0}% complete`;}
  const action=(label,hook,id)=>button(label,`${hook}="${id}"`);
  function toolbar(v){return `<div class="tp-division-actions">${action('+ Participant','data-div-team',v.id)}<span class="tp-desktop-actions">${action('Generate Bracket','data-div-bracket',v.id)}${action('Auto Schedule','data-div-schedule',v.id)}${action('Print','data-tp-print',v.id)}</span><details class="tp-more"><summary>More</summary><div class="tp-menu"><span class="tp-mobile-actions">${action('Generate Bracket','data-div-bracket',v.id)}${action('Auto Schedule','data-div-schedule',v.id)}${action('Print Bracket & Schedule','data-tp-print',v.id)}</span>${action('Edit Division','data-div-edit',v.id)}${action('Manage Prizes','data-div-prizes',v.id)}${action('Winners','data-div-winners',v.id)}${action('Add Match Manually','data-div-match',v.id)}${action('Export DOCX','data-division-docx',v.id)}<hr>${action('Reset Bracket','data-div-reset',v.id)}${action('Delete Division','data-div-del',v.id)}</div></details></div>`;}
  function overview(d,v){const matches=v.matches||[],done=matches.filter(m=>['completed','bye'].includes(m.status)).length,live=matches.filter(m=>m.status==='live'),next=matches.filter(m=>!['completed','cancelled','bye','live'].includes(m.status)).sort(sortMatch).slice(0,3);return `<h2>${E(v.name)} <small>${E(L(v.match_type))}</small></h2><div class="tp-metrics">${[[v.teams?.length||0,'Teams'],[matches.length,'Matches'],[done,'Completed'],[live.length,'Live'],[money((v.prizes||[]).reduce((n,p)=>n+Number(p.amount||0),0)),'Prize pool'],[(matches.length?Math.round(done/matches.length*100):0)+'%','Complete']].map(([n,l])=>`<div><strong>${E(n)}</strong><span>${l}</span></div>`).join('')}</div><p class="tp-muted">${E(L(v.competition_format))} · ${E(L(v.seeding_method))} seeding · ${v.match_duration_minutes||30} minute matches · ${v.rest_minutes??0} minute rest</p>${v.description?`<p>${E(v.description)}</p>`:''}${live.length?'<h3>Live now</h3><div class="tp-match-grid">'+live.slice(0,3).map(m=>matchCard({...m,tournament_id:d.tournament.id,division_name:v.name})).join('')+'</div>':''}<h3>Next matches</h3><div class="tp-match-grid">${next.map(m=>matchCard({...m,tournament_id:d.tournament.id,division_name:v.name})).join('')||empty('No upcoming matches','Generate the draw or check the Schedule tab for completed results.')}</div>`;}
  const sortMatch=(a,b)=>String(a.scheduled_date||'9999').localeCompare(b.scheduled_date||'9999')||String(a.scheduled_time||'99:99').localeCompare(b.scheduled_time||'99:99')||Number(a.match_number||a.id)-Number(b.match_number||b.id);
  function scheduleTable(v,admin=false){const matches=(v.matches||[]).slice().sort(sortMatch);if(!matches.length)return empty('Schedule not available','Generate the draw and assign dates, times and courts.');return `<div class="tp-table-scroll"><table class="tp-table tp-schedule-table"><thead><tr>${['Match #','Round','Date','Time','Court','Team / Player A','Team / Player B','Score','Status','Scorer'].map(t=>`<th scope="col">${t}</th>`).join('')}${admin?'<th scope="col">Actions</th>':''}</tr></thead><tbody>${matches.map(m=>`<tr data-schedule-match="${m.id}">${[m.match_number||m.id,L(m.round),m.scheduled_date?date(m.scheduled_date):'TBA',m.scheduled_time?time(m.scheduled_time):'TBA',m.court_name||'TBA',m.team_a?.name||m.team_a_name||'TBA',m.team_b?.name||m.team_b_name||(m.status==='bye'?'BYE':'TBA'),root.PikolTournamentUI.scoreText(m,'a')+' – '+root.PikolTournamentUI.scoreText(m,'b'),L(m.status),m.scorer_name||'Unassigned'].map((t,i)=>`<td data-label="${['Match #','Round','Date','Time','Court','Team / Player A','Team / Player B','Score','Status','Scorer'][i]}">${E(t)}</td>`).join('')}${admin?`<td data-label="Actions">${button('Review match',`data-tp-match="${m.id}"`)}</td>`:''}</tr>`).join('')}</tbody></table></div>`;}
  function participants(v,admin){return `<h2>Participants <small>${v.teams?.length||0} official teams</small></h2><div class="tp-participant-list">${(v.teams||[]).map(t=>`<article class="tp-participant" role="button" tabindex="0" data-card-nav data-tp-team="${t.id}" aria-label="Open ${E(t.name)} identity">${people(t)}<span><strong>${E(t.name)}</strong><small>${E((t.members||[]).map(p=>p.display_name||p.full_name||'Player').join(' / '))}</small></span><span>${t.seed?'Seed '+E(t.seed):'Unseeded'}</span>${badge('approved','Official')}</article>`).join('')||empty('No official participants','Approved registrations become official teams here.')}</div>`;}
  function workspaceContent(d,v,active,admin=false){if(active==='bracket')return `<h2>${E(v.name)} Bracket</h2><p class="tp-muted">${E(L(v.competition_format))} · Scroll within the bracket to follow every round.</p>${bracket(v)}`;if(active==='schedule')return `<h2>Match Schedule</h2>${scheduleTable(v,admin)}`;if(active==='participants')return participants(v,admin);if(active==='standings')return `<h2>Standings</h2>${standings(v)}`;return overview(d,v);}
  function renderDetail(){const d=detail,t=d.tournament;q('#tn-detail-view').innerHTML=`<section class="tp-tournament-summary"><div class="tp-section-head">${button('← All tournaments','data-tp-discovery')}<div class="tp-actions">${button('Teams & Identity ('+d.divisions.reduce((n,v)=>n+(v.teams||[]).length,0)+')','data-tp-identity')}${cta(t)}</div></div><div class="tp-summary-title"><div><h1>${E(t.name)}</h1>${facts(t)}<p>${E(t.description||'')}</p>${stats(t,d)}</div>${status(t)}</div></section>${workspace(d,divisionId,tab)}`;requestAnimationFrame(drawConnections);}
  function nativeHost(result){return result?.host||result;}
  function winners(v){
    const r=v.results||{finalized:false,placements:[1,2,3].map(place=>({place,status:'pending'}))};
    return `<div class="tp-winners"><p class="tp-result-note">${r.finalized?'Official results':'Competition in progress'} · ${E(v.name)}</p><p class="tp-muted">${E(r.reason||'Complete the deciding matches to confirm official placements.')}</p><div class="tp-placement-grid">${r.placements.map(p=>{
      const t=(v.teams||[]).find(t=>t.id===p.team_id),prize=(v.prizes||[]).find(x=>x.place===p.place),name=p.place===1?'Champion':p.place===2?'Runner-Up':'Third Place';
      return `<article class="tp-placement tp-place-${p.place}"><header>${icon('trophy')}<strong>${name}</strong>${badge(p.status==='official'?'completed':'pending',p.status==='official'?'Official':p.status==='not_contested'?'Not Contested':'Pending')}</header>${t?banner(t):'<div class="tp-result-placeholder">'+icon('trophy')+'</div>'}<div class="tp-placement-body"><h3>${t?E(t.name):p.status==='not_contested'?'Not Contested':'Awaiting results'}</h3>${t?people(t)+(t.members||[]).map(memberRow).join(''):''}${prize?'<p class="tp-prize">'+E(money(prize.amount))+' · '+E(prize.label)+'</p>':''}</div></article>`;
    }).join('')}</div>${r.final_match?`<p class="tp-final-result">${E(L(r.final_match.round))}: ${E((v.teams||[]).find(t=>t.id===r.final_match.team_a_id)?.name)} <strong>${Number(r.final_match.score_a)} – ${Number(r.final_match.score_b)}</strong> ${E((v.teams||[]).find(t=>t.id===r.final_match.team_b_id)?.name)}</p>`:''}</div>`;
  }
  function identity(d,c,admin=false,teamId){const previous=document.activeElement,result=c.modal({title:'Teams & Identity',wide:true,cancelText:'Close',body:'<div class="tp-identity-content"></div>'}),host=nativeHost(result);if(!host)return;const dialog=q('.modal',host);dialog.classList.add('tp-identity-dialog');const area=q('.tp-identity-content',host);let selectedTeamId=teamId||null,filter=String(selectedDivision(d,admin?root.PikolTournamentCommand?.selectedDivision():divisionId)?.id||''),term='';
    function showTeam(id){selectedTeamId=Number(id);const v=d.divisions.find(v=>v.teams.some(t=>t.id===Number(id))),t=v?.teams.find(t=>t.id===Number(id));if(!t)return;area.innerHTML=button('← Team list','data-identity-back')+teamCard(t,v,admin)+`${admin?'<details class="tp-more"><summary>Team actions</summary><div class="tp-menu">'+action('Remove Participant','data-team-del',t.id)+'</div></details>':''}`;}
    function listTeams(){selectedTeamId=null;const rows=d.divisions.filter(v=>!filter||String(v.id)===filter).flatMap(v=>v.teams.map(t=>({v,t}))).filter(({t})=>(t.name+' '+t.members.map(p=>p.display_name||p.full_name).join(' ')).toLowerCase().includes(term));area.innerHTML=`<div class="tp-identity-filters"><label>Division<select class="select" data-identity-division><option value="">All divisions</option>${d.divisions.map(v=>`<option value="${v.id}" ${String(v.id)===filter?'selected':''}>${E(v.name)} · ${E(L(v.match_type))}</option>`).join('')}</select></label><label>Search teams or players<input class="input" type="search" data-identity-search value="${E(term)}"></label></div><div class="tp-identity-list">${rows.map(({t,v})=>`<button class="tp-identity-row" data-identity-team="${t.id}">${people(t)}<span><strong>${E(t.name)}</strong><small>${E(v.name)} · ${E((t.members||[]).map(p=>p.display_name||p.full_name).join(' / '))}</small></span><small>${t.banner_url?'Banner configured':'No banner'}</small></button>`).join('')||empty('No teams match your search')}</div>`;q('[data-identity-search]',area).oninput=e=>{term=e.target.value.toLowerCase();const start=e.target.selectionStart;listTeams();const el=q('[data-identity-search]',area);el.focus();el.setSelectionRange(start,start);};q('[data-identity-division]',area).onchange=e=>{filter=e.target.value;listTeams();};}
    host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-identity-team'))showTeam(b.dataset.identityTeam);if(b.hasAttribute('data-identity-back'))listTeams();if(b.hasAttribute('data-tp-team-edit'))editTeam(Number(b.dataset.tpTeamEdit),c,d,refreshIdentity);});host.addEventListener('change',e=>{if(e.target.matches('[data-tp-banner]'))uploadBanner(e.target,c,refreshIdentity);});if(teamId)showTeam(teamId);else listTeams();async function refreshIdentity(){d=await c.api((admin?'/api/admin/tournaments/':'/api/tournaments/')+d.tournament.id);await c.open(d.tournament.id);if(selectedTeamId)showTeam(selectedTeamId);else listTeams();}}
  function matchDetail(m,c,admin=false){if(!m)return;const result=c.modal({title:'Match '+(m.match_number||m.id),wide:admin,cancelText:'Close',body:admin&&c.matchOperations?c.matchOperations(m):`<div class="tp-rule-card"><h3>${E(m.team_a?.name||m.team_a_name||'TBA')} vs ${E(m.team_b?.name||m.team_b_name||'TBA')}</h3><p>${E(L(m.round))} · ${E(m.court_name||'Court TBA')}</p><p>${E(m.scheduled_date?date(m.scheduled_date):'Date TBA')} · ${m.scheduled_time?time(m.scheduled_time):'Time TBA'}</p><p>${badge(m.status)} ${root.PikolTournamentUI.scoreText(m,'a')} – ${root.PikolTournamentUI.scoreText(m,'b')}</p><a class="tp-btn tp-outline" href="scoring.html?match=${m.id}&display=1">Public Scoreboard</a></div>`});const host=nativeHost(result);if(admin&&host){if(['completed','cancelled','live'].includes(m.status))qa('[data-mfield]',host).forEach(el=>el.disabled=true);if(m.source_key)qa('[data-mfield=team_a_id],[data-mfield=team_b_id]',host).forEach(el=>el.disabled=true);if(['completed','cancelled'].includes(m.status))qa('[data-score]',host).forEach(el=>el.disabled=true);}}
  function handlePlayerClick(e){let b=e.target.closest('button,a,input,label.tp-btn');const card=e.target.closest('[data-card-nav]');if(card&&(!b||b===card))b=card;if(!b)return;if(b.hasAttribute('data-tp-discovery'))ctx.discovery();if(b.hasAttribute('data-tp-open'))ctx.open(Number(b.dataset.tpOpen),b.dataset.openTab);if(b.hasAttribute('data-tp-register')){const t=list.find(t=>t.id===Number(b.dataset.tpRegister))||detail?.tournament;ctx.register(Number(b.dataset.tpRegister),t?.name||'Tournament');}if(b.hasAttribute('data-tp-tab')){tab=b.dataset.tpTab;renderDetail();q('[data-tp-tab="'+tab+'"]').focus({preventScroll:true});}if(b.hasAttribute('data-tp-identity'))identity(detail,ctx);if(b.hasAttribute('data-tp-team'))identity(detail,ctx,false,b.dataset.tpTeam);if(b.hasAttribute('data-tp-match'))matchDetail(findMatch(b.dataset.tpMatch),ctx);if(b.hasAttribute('data-tp-calendar'))calendar(findMatch(b.dataset.tpCalendar));}
  function handleChange(e){if(e.target.hasAttribute('data-tp-select-division')){divisionId=Number(e.target.value);renderDetail();q('[data-tp-select-division]').focus({preventScroll:true});}}
  document.addEventListener('keydown',e=>{const active=e.target.closest('.tp-workspace-tabs [role=tab]');if(active&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const buttons=qa('[role=tab]',active.parentElement),i=buttons.indexOf(active),n=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[n].click();}if(e.key==='Escape')qa('.tp-more[open]').forEach(el=>el.open=false);});
  document.addEventListener('click',e=>{qa('.tp-more[open]').forEach(el=>{if(!el.contains(e.target)||e.target.closest('button'))el.open=false;});});
  setInterval(()=>{if(!document.hidden&&ctx&&detail&&!q('#tab-tournaments').classList.contains('hidden')&&!q('.modal-host')&&!q('.tp-more[open]'))open(detail.tournament.id,ctx,null,true);},12000);
  async function printDivision(d,v,c){const win=root.open('','_blank');if(!win){c.toast('Allow popups to open the print preview.','error');return;}win.document.body.textContent='Preparing selected division…';try{const css=await fetch('tournament-premium.css?v=67').then(r=>r.text());win.document.open();win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${E(d.tournament.name)} — ${E(v.name)} — Bracket & Schedule</title><style>${css}</style></head><body class="tp-print"><header><p>PIKOL · TOURNAMENT BRACKET & SCHEDULE</p><h1>${E(d.tournament.name)}</h1><h2>${E(v.name)} · ${E(L(v.match_type))}</h2>${facts(d.tournament)}<p>${E(L(v.competition_format))} · Generated ${E(new Date().toLocaleString())}</p></header>${paperBracket(v,d.tournament)}<section class="tp-print-schedule"><h2>Match Schedule</h2>${scheduleTable(v)}</section><footer>PIKOL · ${E(d.tournament.name)} · ${E(v.name)} · ${E(L(v.match_type))} · Schedule may change; check PIKOL for live updates.</footer></body></html>`);win.document.close();await win.document.fonts.ready;await new Promise(resolve=>win.requestAnimationFrame(()=>win.requestAnimationFrame(resolve)));let chunk=3;while(chunk>1){const first=win.document.querySelector('.tp-print-bracket'),header=win.document.querySelector('body>header');if(!first||first.getBoundingClientRect().height+(header?.getBoundingClientRect().height||0)<700)break;chunk--;win.document.querySelectorAll('.tp-print-bracket').forEach(el=>el.remove());win.document.querySelector('.tp-print-schedule').insertAdjacentHTML('beforebegin',paperBracket(v,d.tournament,chunk));}drawConnections(win.document);win.focus();win.print();}catch(error){win.document.body.textContent='Print preview failed: '+error.message;c.toast(error.message,'error');}}
  function paperBracket(v,tournament,chunk=3){if(!(v.matches||[]).length)return bracket(v);const groups=new Map();v.matches.filter(m=>!(m.status==='cancelled'&&m.conditional_match)).forEach(m=>{const key=m.group_name||m.bracket_side||m.stage||'Matches';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(m);});return Array.from(groups,([name,matches])=>{const rounds=root.PikolTournamentUI.roundGroups(matches),first=rounds[0].matches;if(first.length<=4&&(chunk===3||first.length<=chunk))return `<section class="tp-print-bracket">${bracket({...v,matches})}</section>`;const pages=[];for(let i=0;i<first.length;i+=chunk){const chosen=new Set(first.slice(i,i+chunk).map(m=>m.id));let changed=true;while(changed){changed=false;matches.forEach(m=>{if(chosen.has(m.id)&&m.next_match_id&&!chosen.has(m.next_match_id)){chosen.add(m.next_match_id);changed=true;}});}if(matches.every(m=>m.stage==='group'))rounds.slice(1).forEach(r=>r.matches.slice(i,i+chunk).forEach(m=>chosen.add(m.id)));pages.push(`<section class="tp-print-bracket"><p class="tp-print-segment">${E(tournament.name)} · ${E(v.name)} · ${E(L(name))} · Draw segment ${pages.length+1} · Later rounds repeat for context</p>${bracket({...v,matches:matches.filter(m=>chosen.has(m.id))})}</section>`);}return pages.join('');}).join('');}
  function node(m){return `<article class="tp-bracket-match ${m.status==='live'?'is-live':''}" data-match-id="${m.id}" data-next="${m.next_match_id||''}"><header>${badge(m.status)}<small>Match ${m.match_number||m.id}</small></header>${['a','b'].map(side=>{const t=m['team_'+side];return `<div class="tp-bracket-team ${m.winner_team_id&&m.winner_team_id===m['team_'+side+'_id']?'is-winner':''}"><span>${t?.seed?`<small>#${t.seed} </small>`:''}${E(t?.name||m['team_'+side+'_name']||(m.status==='bye'?'BYE':'TBA'))}<small class="tp-node-players">${E((t?.members||[]).map(p=>p.display_name||p.full_name).join(" / "))}</small></span><b>${root.PikolTournamentUI.scoreText(m,side)}</b></div>`;}).join('')}<footer>${E(m.court_name||'Court TBA')} · ${E(m.scheduled_time?time(m.scheduled_time):L(m.round))}${m.status==='live'?`<a href="scoring.html?match=${m.id}&display=1" aria-label="Live score match ${m.id}">${icon('live')}</a>`:''}</footer></article>`;}
  function bracket(v){if(!v||(v.matches||[]).length===0)return empty('Bracket not generated','Official pairings appear here when the organiser generates the draw.');const lanes=new Map();v.matches.filter(m=>!(m.status==='cancelled'&&m.conditional_match)).forEach(m=>{const key=m.group_name?'Group '+m.group_name:L(m.bracket_side||m.stage||'Matches');if(!lanes.has(key))lanes.set(key,[]);lanes.get(key).push(m);});return `<div class="tp-bracket-viewport" tabindex="0" aria-label="${E(v.name)} bracket. Scroll horizontally to see every round.">${Array.from(lanes,([name,matches])=>{const rounds=root.PikolTournamentUI.roundGroups(matches);const isPool=matches.every(m=>m.stage==='group');const final=matches.find(m=>['final','grand_final','reset_final'].includes(m.round)&&m.status==='completed'&&!m.next_match_id&&!(m.stage==='grand_final'&&v.matches.some(x=>x.stage==='reset_final'&&x.status!=='cancelled'&&!x.conditional_match)));return `<section class="tp-bracket-lane"><h3>${E(name)}</h3><div style="--tp-round-count:${rounds.length}" class="tp-bracket-rounds ${isPool?'is-pool':''}">${rounds.map(r=>`<section class="tp-bracket-round"><h4>${E(L(r.matches[0].round))}</h4><div class="tp-round-nodes">${r.matches.map(node).join('')}</div></section>`).join('')}${!isPool&&matches.some(m=>['final','grand_final','reset_final'].includes(m.round))?`<div class="tp-champion">${icon('trophy')}<span>CHAMPION</span><b>${final?E(final.team_a_id===final.winner_team_id?final.team_a?.name||final.team_a_name:final.team_b?.name||final.team_b_name):'To be decided'}</b><small>${E(v.name)}</small></div>`:''}</div></section>`;}).join('')}</div>`;}
  function standings(v){if(!v)return empty('Select a division');if(!['round_robin','group_knockout'].includes(v.competition_format))return empty('Knockout results','Winners and advancement are shown in the live bracket for this division.');const groups=v.group_standings?.length?v.group_standings:[{group_name:'',standings:v.standings||[]}];return groups.map(g=>`<section class="tp-pool"><h3>${E(g.group_name?'Group '+g.group_name:v.name)}</h3><div class="tp-table-scroll"><table class="tp-table"><thead><tr><th>Rank / Team</th><th>Played</th><th>Won</th><th>Lost</th><th>Points +/−</th><th>Points</th></tr></thead><tbody>${g.standings.map((r,i)=>`<tr><td><span class="tp-row"><b>${i+1}</b>${people(v.teams.find(t=>t.id===r.team_id))}${E(r.name)}</span></td><td>${r.played}</td><td>${r.wins}</td><td>${r.losses}</td><td>${r.diff}</td><td><b>${r.points}</b></td></tr>`).join('')}</tbody></table></div></section>`).join('');}
  function findMatch(id){return myMatches.concat(detail?allMatches(detail):[]).find(m=>m.id===Number(id));}
  function calendar(m){if(!m?.scheduled_date||!m.scheduled_time)return;const escapeIcs=v=>String(v||'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const start=m.scheduled_date.replace(/-/g,'')+'T'+m.scheduled_time.replace(/:/g,'').slice(0,4)+'00';const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//PIKOL//Tournament//EN','BEGIN:VEVENT','UID:pikol-match-'+m.id+'@'+location.host,'DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),'DTSTART;TZID='+(ctx?.brand().facility_timezone||'Asia/Manila')+':'+start,'DURATION:PT'+Math.max(10,Number(m.match_duration_minutes||(detail?.divisions||[]).find(v=>v.id===m.division_id)?.match_duration_minutes)||30)+'M','SUMMARY:'+escapeIcs((m.team_a?.name||m.team_a_name||'TBA')+' vs '+(m.team_b?.name||m.team_b_name||'TBA')),'LOCATION:'+escapeIcs(m.court_name),'DESCRIPTION:'+escapeIcs((m.tournament_name||detail?.tournament.name||'Tournament')+' · '+(m.division_name||'')+' · Check PIKOL for schedule updates.'),'END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/calendar'})),a=document.createElement('a');a.href=url;a.download='PIKOL-match-'+m.id+'.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function jpeg(file){if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPEG, PNG or WebP image.');if(file.size>12*1024*1024)throw new Error('Choose an image smaller than 12 MB.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});return root.PikolVenueUI?root.PikolVenueUI.optimize(data,'team'):data;}
  async function uploadBanner(input,c,refresh){if(!input.files[0])return;input.disabled=true;try{const data_url=await jpeg(input.files[0]);await c.api('/api/tournament-teams/'+input.dataset.tpBanner+'/banner',{method:'POST',body:{data_url}});c.toast('Team banner saved.','success');await refresh();}catch(error){c.toast(error.message,'error');}finally{input.disabled=false;input.value='';}}
  function editTeam(id,c,d,refresh){const team=d.divisions.flatMap(v=>v.teams).find(t=>t.id===id);if(!team)return;c.modal({title:'Team identity',confirmText:'Save team name',body:`<label class="label" for="tp-team-name">Team name</label><input class="input" id="tp-team-name" maxlength="120" value="${E(team.name)}">`,onConfirm:async host=>{await c.api('/api/tournament-teams/'+id+'/identity',{method:'PUT',body:{name:q('#tp-team-name',host).value}});if(refresh)await refresh();else if(c===ctx)await open(d.tournament.id,c,null,true);else c.open(d.tournament.id);}});}
  function drawConnections(scope=document){if(!scope || typeof scope.querySelectorAll!=='function')scope=document;qa('.tp-workspace-tabs',scope).forEach(nav=>{const active=q('[aria-selected=true]',nav);if(!active)return;const a=active.getBoundingClientRect(),n=nav.getBoundingClientRect();if(a.right>n.right)nav.scrollLeft+=a.right-n.right+8;else if(a.left<n.left)nav.scrollLeft-=n.left-a.left+8;});
    qa('.tp-bracket-rounds:not(.is-pool)',scope).forEach(board=>{
      board.querySelector('.tp-connectors')?.remove();
      const rect=board.getBoundingClientRect(),ns='http://www.w3.org/2000/svg',svg=board.ownerDocument.createElementNS(ns,'svg');
      svg.classList.add('tp-connectors');svg.setAttribute('aria-hidden','true');svg.setAttribute('width',board.scrollWidth);svg.setAttribute('height',board.scrollHeight);
      qa('[data-match-id]',board).forEach(node=>{const next=q('[data-match-id="'+node.dataset.next+'"]',board);if(!next)return;const a=node.getBoundingClientRect(),b=next.getBoundingClientRect(),x1=a.right-rect.left,y1=a.top+a.height/2-rect.top,x2=b.left-rect.left,y2=b.top+b.height/2-rect.top;if(x2<x1)return;const mid=(x1+x2)/2,path=board.ownerDocument.createElementNS(ns,'path');path.setAttribute('d','M'+x1+' '+y1+' H'+mid+' V'+y2+' H'+x2);path.setAttribute('fill','none');path.setAttribute('stroke',node.querySelector('.is-winner')?'#008963':'#668779');path.setAttribute('stroke-width','1.6');svg.appendChild(path);});board.prepend(svg);
    });
  }
  let connectionResize;window.addEventListener('resize',()=>{clearTimeout(connectionResize);connectionResize=setTimeout(drawConnections,120);});

 root.PikolPremium={winners,drawConnections,load,open,setup,avatar,people,picture,teamCard,memberRow,matchCard,bracket,standings,icon,badge,banner,asset,date,time,label:L,esc:E,jpeg,uploadBanner,editTeam,stats,allMatches,workspace,workspaceContent,scheduleTable,overview,identity,printDivision,matchDetail,bindCards,setAdminContext:c=>{adminCtx=c;},getContext:()=>ctx};
})(window);

(function(root){'use strict';
 const P=root.PikolPremium,q=(s,h)=>h.querySelector(s);
 function step(host,n){host.dataset.premiumStep=String(n);host.querySelectorAll('[data-registration-step]').forEach(el=>el.classList.toggle('tp-step-hidden',Number(el.dataset.registrationStep)!==n));host.querySelectorAll('.tp-steps li').forEach((el,i)=>el.classList.toggle('is-active',i===n-1));const confirm=q('[data-confirm]',host),label=n===1?'Continue to Division →':'Submit & Continue to Payment →';confirm.textContent=label;if(confirm.classList.contains('is-loading'))confirm.dataset.text=label;const back=q('[data-registration-back]',host);if(back)back.classList.toggle('hidden',n===1);}
 function enhance(host,user,info){const dialog=q('.modal',host),fields=q('.registration-fields',host);if(!fields)return;dialog.classList.add('tp-registration-dialog');q('.registration-player',host)?.remove();fields.insertAdjacentHTML('afterbegin',`<ol class="tp-steps"><li><b>1</b>Player / Team</li><li><b>2</b>Division</li><li><b>3</b>Payment</li><li><b>4</b>Confirmation</li></ol><div class="tp-registration-player" data-registration-step="1">${P.avatar(user,true)}<span><strong>${P.esc(user?.full_name||'Player')}</strong><small>${P.esc(info.player_division)} · Official division</small></span></div>`);
  ['#tr-team','#tr-partner-name'].forEach(sel=>{const el=q(sel,host);if(el){const container=sel==='#tr-partner-name'?q('#tr-partner',host):el.closest('.field');container.dataset.registrationStep='1';}});
  ['#tr-division','#tr-notes','#tr-use-credit'].forEach(sel=>{const el=q(sel,host);if(el){let container=el.closest('.field')||el.closest('label')||el.parentElement;container.dataset.registrationStep='2';}});
  q('.info-callout',fields).dataset.registrationStep='2';
  const back=document.createElement('button');back.type='button';back.className='btn btn-outline hidden';back.dataset.registrationBack='';back.textContent='← Player / Team';back.onclick=()=>step(host,1);q('.modal-foot',host).prepend(back);step(host,1);
 }
 function confirmation(modal,r,money){modal({title:'Registration received',body:`<div class="tp-surface"><ol class="tp-steps"><li><b>✓</b>Player / Team</li><li><b>✓</b>Division</li><li><b>✓</b>Payment</li><li class="is-active"><b>4</b>Confirmation</li></ol><h2>You're registered</h2><p>Registration #${P.esc(r.registration.id)} is pending organiser approval.</p><p>Payment status: ${P.esc(P.label(r.registration.payment_status))}</p><p>PIKOL Credit used: ${money(r.credit_used)}</p><p>Follow the status in My Registrations.</p></div>`});}
 root.PikolPremiumRegistration={step,enhance,confirmation};
})(window);
