/* PIKOL tournament presentation. All operational actions use the existing application/API. */
(function(root){
  'use strict';
  const E=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const L=v=>String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
  const q=(s,h=document)=>h.querySelector(s);
  const qa=(s,h=document)=>Array.from(h.querySelectorAll(s));
  const fallback='assets/booking/hero-court.jpg';
  const paths={trophy:'M7 3h10v6a5 5 0 0 1-10 0V3Zm0 2H3v3a4 4 0 0 0 4 4m10-7h4v3a4 4 0 0 1-4 4m-5 2v6m-4 1h8',calendar:'M8 2v4m8-4v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14H3V6a2 2 0 0 1 2-2Zm2 10h3v3H7Z',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-3.87M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm8 0a4 4 0 0 1 0 8',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Zm-5 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',clock:'M12 8v5l3 2m7-3a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z',grid:'M3 3h7v7H3Zm11 0h7v7h-7ZM3 14h7v7H3Zm11 0h7v7h-7Z',home:'m3 10 9-8 9 8v11h-6v-7H9v7H3V10Z',live:'M9 5a8 8 0 0 0 0 14m6-14a8 8 0 0 1 0 14M7 2a12 12 0 0 0 0 20M17 2a12 12 0 0 1 0 20M12 10v4',bracket:'M3 3h5v5H3Zm0 13h5v5H3Zm13-7h5v5h-5ZM8 5h4v14H8m4-7h4',search:'M16 16l6 6M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z',arrow:'M4 12h16m-6-6 6 6-6 6',check:'m4 12 5 5L20 6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',bell:'M18 8a6 6 0 0 0-12 0v7l-2 3h16l-2-3V8Zm-9 13h6',money:'M3 5h18v14H3Zm9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z',chart:'M3 13h4v8H3Zm7-7h4v15h-4Zm7-4h4v19h-4Z',ball:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0ZM8 7h.01M15 6h.01M6 13h.01M12 12h.01M18 13h.01M9 18h.01M16 18h.01'};
  const icon=(name,cls='')=>`<svg class="tp-icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.trophy}"/></svg>`;
  let ctx=null,epoch=0,detail=null,tab='overview',divisionId=null,filters={date:'',court:'',status:''},list=[],myMatches=[],selected=null,adminCtx=null,adminData=null;
  const asset=v=>{const s=String(v||'');if(!s)return '';if(/^https?:\/\//i.test(s))return s;if(s.startsWith('/branding/'))return (root.PIKOL_API_BASE||'')+s;if(/^assets\//.test(s))return s;return '';};
  const initials=name=>String(name||'?').trim().split(/\s+/).slice(0,2).map(s=>s[0]).join('').toUpperCase();
  const hue=name=>Array.from(String(name||'')).reduce((a,c)=>a+c.charCodeAt(0)*11,0)%360;
  const date=v=>v?new Date(v.slice(0,10)+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Date to be announced';
  const time=v=>v?new Date('2000-01-01T'+v).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'}):'Time TBA';
  const money=n=>ctx?ctx.money(Number(n||0)):adminCtx?adminCtx.money(Number(n||0)):new Intl.NumberFormat(undefined,{style:'currency',currency:'PHP'}).format(Number(n||0));
  const button=(text,attrs='',kind='outline')=>`<button type="button" class="tp-btn tp-${kind}" ${attrs}>${text}</button>`;
  const empty=(title,msg='')=>`<div class="tp-empty"><span>${icon('trophy')}</span><strong>${E(title)}</strong><p>${E(msg)}</p></div>`;
  const badge=(status,text)=>`<span class="tp-badge tp-status-${E(status)}">${['live','ongoing'].includes(status)?'<i></i>':''}${E(text||L(status))}</span>`;
  const status=t=>t.registration_open?badge('open','Registration open'):badge(t.status,['published','registration_open'].includes(t.status)?'Registration closed':null);
  function avatar(p={},large=false){const name=p.full_name||p.display_name||p.name||'Player',url=asset(p.profile_photo_url);return `<span class="tp-avatar${large?' tp-avatar-lg':''}" style="--avatar-hue:${hue(name)}" title="${E(name)}"><span>${E(initials(name))}</span>${url?`<img src="${E(url)}" alt="${E(name)}" loading="lazy" decoding="async" data-tp-avatar>`:''}</span>`;}
  const people=(team)=>`<span class="tp-avatar-stack">${asset(team?.banner_url)?`<img class="tp-team-badge" src="${E(asset(team.banner_url))}" alt="${E(team.name)} badge" data-tp-avatar>`:''}${(team&&team.members||[]).map(p=>avatar(p)).join('')||avatar({name:team&&team.name||'TBA'})}</span>`;
  const picture=(url,alt='',cls='')=>`<img class="tp-photo ${cls}" src="${E(asset(url)||fallback)}" alt="${E(alt||'Pickleball venue promotional illustration')}" loading="lazy" decoding="async" data-tp-image>`;
  const banner=(team)=>`<div class="tp-team-banner" style="--team-hue:${hue(team.name)}">${asset(team.banner_url)?picture(team.banner_url,team.name+' team banner'):''}<span class="tp-team-monogram">${E(initials(team.name))}</span>${team.seed?`<span class="tp-seed">#${E(team.seed)} SEED</span>`:''}</div>`;
  const rating=p=>p.rating!=null?`★ ${Number(p.rating).toFixed(1)} · `:'';
  const memberRow=p=>`<div class="tp-person">${avatar(p)}<span><strong>${E(p.full_name||p.display_name||'Player')}</strong><small>${rating(p)}${E(p.player_division||'Registered participant')}</small></span></div>`;
  const dateRange=t=>date(t.tournament_date)+(t.end_date&&t.end_date!==t.tournament_date?' – '+date(t.end_date):'');
  function countdown(t){if(!t.registration_open||!t.registration_end)return '';return `<div class="tp-countdown" data-deadline="${E(t.registration_closes_at||t.registration_end)}" aria-label="Registration closes ${E(date(t.registration_end))}"></div>`;}
  function tick(){qa('[data-deadline]').forEach(el=>{const end=new Date(el.dataset.deadline.includes('T')?el.dataset.deadline:el.dataset.deadline+'T23:59:59').getTime();let diff=Math.max(0,Math.floor((end-Date.now())/1000));const parts=[Math.floor(diff/86400),Math.floor(diff/3600)%24,Math.floor(diff/60)%60,diff%60];el.innerHTML=parts.map((n,i)=>`<span><b>${String(n).padStart(2,'0')}</b><small>${['DAYS','HRS','MINS','SECS'][i]}</small></span>`).join('');});}
  setInterval(()=>{if(!document.hidden)tick();},1000);
  document.addEventListener('error',e=>{if(e.target.matches&&e.target.matches('[data-tp-avatar]'))e.target.remove();else if(e.target.matches&&e.target.matches('[data-tp-image]')){if(e.target.dataset.failed)e.target.remove();else{e.target.dataset.failed='1';e.target.src=e.target.closest('.tp-brand')?'icons/icon-192.png':fallback;}}},true);

  function setup(c){ctx=c;const sheet=q('#tab-tournaments');sheet.classList.add('tp-page');if(!q('.tp-sidebar',sheet)){
    const brand=c.brand(),logo=asset(brand.app_logo_url||brand.logo_url)||'icons/icon-192.png';
    sheet.insertAdjacentHTML('afterbegin',`<nav class="tp-sidebar" aria-label="Tournament navigation"><button class="tp-brand" data-tp-nav="dashboard" aria-label="Home"><img src="${E(logo)}" alt="${E(brand.facility_name||'PIKOL')}" data-tp-image></button><button data-tp-nav="dashboard">${icon('home')}<span>Home</span></button><button class="is-active" data-tp-discovery>${icon('calendar')}<span>Events &amp;<br>Registrations</span></button><button data-tp-mymatches>${icon('trophy')}<span>My Matches</span></button><button data-tp-nav="profile">${icon('users')}<span>My Profile</span></button><button data-tp-nav="book">${icon('pin')}<span>Courts &amp; Booking</span></button><button data-tp-nav="membership">${icon('chart')}<span>Membership</span></button><button data-tp-nav="notifications">${icon('bell')}<span>Notifications</span></button><button data-tp-nav="profile">${icon('settings')}<span>Settings</span></button><div class="tp-slogan">Play<br><i>Compete</i><br>Belong<span></span></div></nav><div class="tp-topbar"><label class="tp-search">${icon('search')}<input id="tp-search" type="search" placeholder="Search tournaments, venues, or locations…" aria-label="Search tournaments"></label><div class="tp-account" id="tp-account"></div></div>`);
    const heading=q(':scope > .spread',sheet);heading.classList.add('tp-page-heading');
    q('.page-title',heading).textContent='Tournaments';q('.page-subtitle',heading).textContent='Discover and register for upcoming pickleball tournaments';
    q('#tp-search').addEventListener('input',()=>renderDiscovery());
    sheet.addEventListener('click',handlePlayerClick);
    sheet.addEventListener('change',handleChange);
  }
  const user=c.user();q('#tp-account').innerHTML=user?`${avatar(user)}<span><strong>${E(user.full_name)}</strong><small>${E(user.player_division||'Player')}</small></span>`:button('Sign in','data-tp-nav="profile"','glass');
  }
  function cta(t){return t.registration_open?button('Register Now '+icon('arrow'),`data-tp-register="${t.id}"`,'gold'):button('View Tournament '+icon('arrow'),`data-tp-open="${t.id}"`,'blue');}
  function facts(t,divisions){return `<div class="tp-facts"><span>${icon('pin')}<span><strong>${E(t.venue||t.court_name||ctx?.brand().facility_name||'Venue TBA')}</strong><small>Venue</small></span></span><span>${icon('calendar')}<span><strong>${E(dateRange(t))}</strong><small>${t.start_time?time(t.start_time):'Tournament dates'}</small></span></span>${t.registration_end?`<span class="tp-deadline">${icon('clock')}<span><strong>Registration closes</strong><small>${E(date(t.registration_end))}</small></span></span>`:''}</div>`;}
  function stats(t,d){const teams=d?d.divisions.flatMap(x=>x.teams||[]):[],n=d?new Set(teams.flatMap(x=>x.members.map(m=>m.user_id||'guest'+m.id))).size:Number(t.player_count||0);return `<div class="tp-event-stats"><span>${icon('trophy')}<span><b>${money(d?d.prize_pool:t.prize_pool)}</b><small>Total Prize Pool</small></span></span><span>${icon('users')}<span><b>${d?n:Number(t.team_count||0)}</b><small>${d?'Players':'Official Teams'}</small></span></span><span>${icon('grid')}<span><b>${d?d.divisions.length:Number(t.division_count||0)}</b><small>Divisions</small></span></span></div>`;}
  function eventCard(t){return `<article class="tp-event-card"><button class="tp-card-image" data-tp-open="${t.id}" aria-label="View ${E(t.name)}">${picture(t.poster_url,t.name)}${status(t)}</button><div class="tp-card-body"><h3><button class="tp-text-button" data-tp-open="${t.id}">${E(t.name)}</button></h3><p>${icon('pin')}${E(t.venue||t.court_name||'Venue TBA')}</p><p>${icon('calendar')}${E(dateRange(t))}</p><div class="tp-chips"><span>${Number(t.division_count||0)} divisions</span><span>${Number(t.team_count||0)} teams</span></div><footer><strong>${icon('trophy')}${money(t.prize_pool)} <small>Prize Pool</small></strong><button class="tp-circle" data-tp-open="${t.id}" aria-label="Open ${E(t.name)}">›</button></footer></div></article>`;}
  function spotlight(t){return `<aside class="tp-spotlight tp-surface">${picture(t.poster_url,t.name)}<div class="tp-spotlight-body"><h2>${E(t.name)}</h2>${status(t)}${facts(t)}<div class="tp-mini-tabs"><b>About</b><button data-tp-open="${t.id}" data-open-tab="divisions">Divisions</button><button data-tp-open="${t.id}" data-open-tab="schedule">Schedule</button></div><p>${E(t.description||'Event information, official participants and live results are available on the tournament page.')}</p>${stats(t)}<ul class="tp-benefits"><li>${icon('users')}${Number(t.team_count||0)} official teams</li><li>${icon('grid')}${Number(t.division_count||0)} divisions</li><li>${icon('calendar')}${E(t.start_time?time(t.start_time):'Schedule to be announced')}</li></ul>${cta(t)}<div class="tp-actions">${button(icon('bracket')+' View Bracket',`data-tp-open="${t.id}" data-open-tab="bracket"`)}${button(icon('calendar')+' Schedule',`data-tp-open="${t.id}" data-open-tab="schedule"`)}</div></div></aside>`;}
  function matchCard(m){const a=m.team_a,b=m.team_b;return `<article class="tp-match-card"><div class="tp-row">${badge(m.status)}<small>${E(m.scheduled_date?date(m.scheduled_date):'Schedule TBA')}${m.scheduled_time?' · '+time(m.scheduled_time):''}</small></div><div class="tp-match-division">${E(m.division_name||'')}</div><div class="tp-versus-row"><div>${people(a)}<strong>${E(a?.name||m.team_a_name||'TBA')}</strong></div><b>${['live','completed'].includes(m.status)?`${m.score_a} : ${m.score_b}`:'vs'}</b><div>${people(b)}<strong>${E(b?.name||m.team_b_name||'TBA')}</strong></div></div><p>${icon('pin')}${E(m.court_name||'Court TBA')} · ${E(L(m.round))}</p><div class="tp-actions">${button('View Details',`data-tp-open="${m.tournament_id}" data-open-tab="schedule"`)}${m.status==='live'?`<a class="tp-btn tp-blue" href="scoring.html?match=${m.id}&display=1">${icon('live')} Live Score</a>`:m.status!=='completed'&&m.scheduled_date&&m.scheduled_time?button(icon('calendar')+' Calendar',`data-tp-calendar="${m.id}"`):button('View Bracket',`data-tp-open="${m.tournament_id}" data-open-tab="bracket"`)}</div></article>`;}
  async function load(c){setup(c);const request=++epoch;detail=null;tab='overview';q('#tn-detail-view').classList.add('hidden');q('#tn-list-view').classList.remove('hidden');q('#tab-tournaments').classList.remove('tp-detail-open');q('#tn-list-view').innerHTML=empty('Loading tournaments…');try{const [rows,matches]=await Promise.all([c.api('/api/tournaments'),c.user()?c.api('/api/my/matches'):Promise.resolve([])]);if(request!==epoch)return;list=rows;myMatches=matches;selected=list.find(t=>t.registration_open)||list.find(t=>t.status==='live')||list[0];renderDiscovery();}catch(error){q('#tn-list-view').innerHTML=empty('Could not load tournaments',error.message);}}
  function renderDiscovery(){if(detail||!ctx)return;const term=(q('#tp-search')?.value||'').toLowerCase(),rows=list.filter(t=>(t.name+' '+t.venue+' '+t.description).toLowerCase().includes(term)),t=rows.find(r=>r.id===selected?.id)||rows[0];const visibleMatches=myMatches.filter(m=>m.status!=='cancelled').sort((a,b)=>(a.status==='live'?-1:0)-(b.status==='live'?-1:0));q('#tn-list-view').innerHTML=`<div class="tp-discovery-layout"><main class="tp-main-stack">${t?`<section class="tp-featured">${picture(t.poster_url,t.name)}<div class="tp-featured-content"><div class="tp-row">${badge('featured','★ FEATURED TOURNAMENT')}${countdown(t)}</div><h2>${E(t.name)}</h2>${facts(t)}<p>${E(t.description||'Play. Compete. Belong.')}</p><div class="tp-featured-bottom">${stats(t)}${cta(t)}</div></div></section>`:empty('No tournaments found','Try a different search or check back for published events.')}<section class="tp-surface" id="tp-my-matches"><div class="tp-section-head"><h2>${icon('calendar')} My Matches</h2>${visibleMatches.length>3?button('View all '+visibleMatches.length,'data-tp-allmatches','link'):''}</div><div class="tp-match-grid">${visibleMatches.slice(0,3).map(matchCard).join('')||empty('Your next match starts here',ctx.user()?'Approved entries appear here once matches are generated.':'Sign in to see your tournament schedule.')}</div></section><section class="tp-surface"><div class="tp-section-head"><h2>${icon('calendar')} Browse Tournaments</h2><span class="tp-muted">${rows.length} events</span></div><div class="tp-event-grid">${rows.map(eventCard).join('')}</div></section></main>${t?spotlight(t):''}</div>`;tick();}

  const allMatches=d=>d.divisions.flatMap(v=>(v.matches||[]).map(m=>({...m,tournament_id:d.tournament.id,division_name:v.name,competition_format:v.competition_format})));
  function teamCard(t,d,admin=false){const own=admin||(ctx?.user()&&(t.members||[]).some(m=>m.user_id===ctx.user().id));return `<article class="tp-team-card">${banner(t)}<div><h3>${E(t.name)}</h3><div class="tp-row">${people(t)}<small>${(t.members||[]).length} players</small></div><div class="tp-chips"><span>${E(d.name)}</span>${t.seed?`<span>Seed ${t.seed}</span>`:''}</div>${(t.members||[]).map(memberRow).join('')}${own?`<div class="tp-actions">${button('Edit identity',`data-tp-team-edit="${t.id}"`)}<label class="tp-btn tp-outline">Banner<input type="file" accept="image/jpeg,image/png,image/webp" data-tp-banner="${t.id}" class="tp-file-input" aria-label="Upload banner for ${E(t.name)}"></label></div>`:''}</div></article>`;}
  function divisionsView(d){return `<div class="tp-division-grid">${d.divisions.map(v=>`<article class="tp-division-card"><div class="tp-division-icon" style="--team-hue:${hue(v.name)}">${icon('users')}</div><h3>${E(v.name)}</h3><p>${E(L(v.match_type))} · ${E(L(v.competition_format))}</p><div class="tp-row"><strong>${v.registered??v.teams.length}${v.max_teams?' / '+v.max_teams:''} teams</strong><span>${money(v.entry_fee||d.tournament.registration_fee)}</span></div>${v.max_teams?`<progress max="${v.max_teams}" value="${v.registered??v.teams.length}"></progress>`:''}<p>${E(v.description||'')}</p>${button('View teams',`data-tp-division="${v.id}" data-next-tab="teams"`,'link')}</article>`).join('')||empty('Divisions will be announced soon')}</div>`;}
  function node(m){return `<article class="tp-bracket-match ${m.status==='live'?'is-live':''}" data-match-id="${m.id}" data-next="${m.next_match_id||''}"><header>${badge(m.status)}<small>Match ${m.match_number||m.id}</small></header>${['a','b'].map(side=>{const t=m['team_'+side];return `<div class="tp-bracket-team ${m.winner_team_id&&m.winner_team_id===m['team_'+side+'_id']?'is-winner':''}">${people(t)}<span>${t?.seed?`<small>#${t.seed} </small>`:''}${E(t?.name||m['team_'+side+'_name']||'TBA')}</span><b>${root.PikolTournamentUI.scoreText(m,side)}</b></div>`;}).join('')}<footer>${E(m.court_name||'Court TBA')} · ${E(m.scheduled_time?time(m.scheduled_time):L(m.round))}${m.status==='live'?`<a href="scoring.html?match=${m.id}&display=1" aria-label="Live score match ${m.id}">${icon('live')}</a>`:''}</footer></article>`;}
  function bracket(v){if(!v||(v.matches||[]).length===0)return empty('Bracket not generated','Official pairings appear here when the organiser generates the draw.');const lanes=new Map();v.matches.filter(m=>!(m.status==='cancelled'&&m.conditional_match)).forEach(m=>{const key=m.group_name?'Group '+m.group_name:L(m.bracket_side||m.stage||'Matches');if(!lanes.has(key))lanes.set(key,[]);lanes.get(key).push(m);});return `<div class="tp-bracket-viewport" tabindex="0" aria-label="${E(v.name)} bracket. Scroll horizontally to see every round.">${Array.from(lanes,([name,matches])=>{const rounds=root.PikolTournamentUI.roundGroups(matches);const isPool=matches.every(m=>m.stage==='group');const final=matches.find(m=>['final','grand_final','reset_final'].includes(m.round)&&m.status==='completed'&&!m.next_match_id&&!(m.stage==='grand_final'&&v.matches.some(x=>x.stage==='reset_final'&&x.status!=='cancelled'&&!x.conditional_match)));return `<section class="tp-bracket-lane"><h3>${E(name)}</h3><div class="tp-bracket-rounds ${isPool?'is-pool':''}">${rounds.map(r=>`<section class="tp-bracket-round"><h4>${E(L(r.matches[0].round))}</h4><div class="tp-round-nodes">${r.matches.map(node).join('')}</div></section>`).join('')}${!isPool&&matches.some(m=>['final','grand_final','reset_final'].includes(m.round))?`<div class="tp-champion">${icon('trophy')}<span>CHAMPION</span><b>${final?E(final.team_a_id===final.winner_team_id?final.team_a?.name||final.team_a_name:final.team_b?.name||final.team_b_name):'To be decided'}</b><small>${E(v.name)}</small></div>`:''}</div></section>`;}).join('')}</div>`;}
  function standings(v){if(!v)return empty('Select a division');if(!['round_robin','group_knockout'].includes(v.competition_format))return empty('Knockout results','Winners and advancement are shown in the live bracket for this division.');const groups=v.group_standings?.length?v.group_standings:[{group_name:'',standings:v.standings||[]}];return groups.map(g=>`<section class="tp-pool"><h3>${E(g.group_name?'Group '+g.group_name:v.name)}</h3><div class="tp-table-scroll"><table class="tp-table"><thead><tr><th>Rank / Team</th><th>Played</th><th>Won</th><th>Lost</th><th>Points +/−</th><th>Points</th></tr></thead><tbody>${g.standings.map((r,i)=>`<tr><td><span class="tp-row"><b>${i+1}</b>${people(v.teams.find(t=>t.id===r.team_id))}${E(r.name)}</span></td><td>${r.played}</td><td>${r.wins}</td><td>${r.losses}</td><td>${r.diff}</td><td><b>${r.points}</b></td></tr>`).join('')}</tbody></table></div></section>`).join('');}
  function filteredMatches(d){return allMatches(d).filter(m=>(!divisionId||m.division_id===Number(divisionId))&&(!filters.date||m.scheduled_date===filters.date)&&(!filters.court||m.court_id===Number(filters.court))&&(!filters.status||m.status===filters.status)).sort((a,b)=>String(a.scheduled_date||'9999').localeCompare(b.scheduled_date||'9999')||String(a.scheduled_time||'99:99').localeCompare(b.scheduled_time||'99:99')||a.id-b.id);}
  function schedule(d,limit=0){const matches=filteredMatches(d),dates=[...new Set(allMatches(d).map(m=>m.scheduled_date).filter(Boolean))].sort();return `${limit?'':`<div class="tp-schedule-filters"><select data-tp-filter="date" aria-label="Match date"><option value="">All dates</option>${dates.map(v=>`<option value="${E(v)}" ${v===filters.date?'selected':''}>${E(date(v))}</option>`).join('')}</select><select data-tp-filter="court" aria-label="Match court"><option value="">All courts</option>${(d.courts||[]).map(c=>`<option value="${c.id}" ${String(c.id)===filters.court?'selected':''}>${E(c.name)}</option>`).join('')}</select><select data-tp-filter="status" aria-label="Match status"><option value="">All statuses</option>${['live','scheduled','ready','completed','postponed'].map(v=>`<option ${v===filters.status?'selected':''} value="${v}">${L(v)}</option>`).join('')}</select></div>`}<div class="tp-schedule-grid">${(limit?matches.slice(0,limit):matches).map(m=>`<article class="tp-court-card"><div class="tp-court-cover">${picture((d.courts||[]).find(c=>c.id===m.court_id)?.image_url)}<span>${E(m.court_name||'Court TBA')}${badge(m.status)}</span></div>${matchCard(m)}</article>`).join('')||empty('No matches to show','Change the filters or wait for the organiser to publish the schedule.')}</div>`;}
  function courtView(d){const games=allMatches(d);return `<div class="tp-court-grid">${(d.courts||[]).map(c=>{const queue=games.filter(m=>m.court_id===c.id&&!['completed','cancelled'].includes(m.status)).sort((a,b)=>(a.status==='live'?-1:0)-(b.status==='live'?-1:0)||String(a.scheduled_date+a.scheduled_time).localeCompare(b.scheduled_date+b.scheduled_time));return `<article class="tp-court-card"><div class="tp-court-cover">${picture(c.image_url)}<span>${E(c.name)}${badge(queue[0]?.status||'available',queue.length?queue[0].status==='live'?'LIVE NOW':'UP NEXT':'AVAILABLE')}</span></div>${queue.length?matchCard(queue[0]):empty('Waiting for the next match')}<details><summary>Upcoming on ${E(c.name)} (${Math.max(0,queue.length-1)})</summary>${queue.slice(1).map((m,i)=>`<div class="tp-queue-row">${badge('scheduled',i===0?'ON DECK':'SCHEDULED')}<strong>${E(m.team_a?.name||'TBA')} vs ${E(m.team_b?.name||'TBA')}</strong><small>${E(date(m.scheduled_date))} · ${time(m.scheduled_time)} · ${E(m.division_name)}</small></div>`).join('')||'<p class="tp-muted">No further matches assigned.</p>'}</details></article>`;}).join('')||empty('No courts assigned')}</div>`;}

  function registrationPanel(d){const t=d.tournament,user=ctx.user();return `<aside class="tp-registration tp-surface"><div class="tp-section-head"><h2>Registration</h2>${status(t)}</div><ol class="tp-steps"><li class="is-active"><b>1</b>Player / Team</li><li><b>2</b>Division</li><li><b>3</b>Payment</li><li><b>4</b>Confirm</li></ol><h3>Player Information</h3>${user?memberRow({...user,display_name:user.full_name}):empty('Join the competition','Sign in to register your player or team.')}<h3>Division &amp; Team</h3><p class="tp-muted">Choose your eligible division and registered partner. Your official player division is checked at registration.</p>${d.divisions.map(v=>`<div class="tp-registration-division"><span>${icon('users')}<strong>${E(v.name)}</strong><small>${E(L(v.match_type))}</small></span><b>${money(v.entry_fee||t.registration_fee)}</b></div>`).join('')}<div class="tp-fee-note">Entry fees are per registration. Membership discounts and available PIKOL Credit are applied at checkout.</div>${t.registration_open?cta(t):`<p>${E(t.status==='cancelled'?'This event has been cancelled.':'Registration is currently closed.')}</p>`}<div class="tp-secure">${icon('check')} Existing payment methods · Receipt verification</div>${t.registration_end?`<div class="tp-closes"><h3>${icon('clock')} Registration closes in</h3>${countdown(t)}<small>${E(date(t.registration_end))} · Venue time</small></div>`:''}</aside>`;}
  async function open(id,c,requestedTab,silent){setup(c);const request=++epoch;if(detail?.tournament.id!==Number(id)){tab=requestedTab||'overview';divisionId=null;filters={date:'',court:'',status:''};}else if(requestedTab)tab=requestedTab;q('#tn-list-view').classList.add('hidden');q('#tn-detail-view').classList.remove('hidden');q('#tab-tournaments').classList.add('tp-detail-open');if(!silent)q('#tn-detail-view').innerHTML=empty('Loading tournament…');try{const d=await c.api('/api/tournaments/'+id);if(request!==epoch)return;if(silent&&JSON.stringify(detail)===JSON.stringify(d))return;const previousScroll=silent?qa('.tp-bracket-viewport').map(el=>[el.scrollLeft,el.scrollTop]):[];
const focus=silent&&document.activeElement?.matches('[data-tp-select-division],[data-tp-filter]')?document.activeElement.outerHTML:null;
detail=d;renderDetail();if(silent){qa('.tp-bracket-viewport').forEach((el,i)=>{if(previousScroll[i]){el.scrollLeft=previousScroll[i][0];el.scrollTop=previousScroll[i][1];}});if(focus)qa('[data-tp-select-division],[data-tp-filter]').find(el=>el.outerHTML===focus)?.focus({preventScroll:true});}}catch(error){if(request!==epoch)return;q('#tn-detail-view').innerHTML=empty('Unable to load tournament',error.message)+button('All tournaments','data-tp-discovery');}}
  function renderDetail(){if(!detail)return;const d=detail,t=d.tournament,liveMode=['bracket','schedule','courts','standings'].includes(tab);const v=d.divisions.find(x=>x.id===Number(divisionId))||d.divisions[0];const tabs=[['overview','home','Overview'],['divisions','trophy','Divisions'],['teams','users','Teams'],['players','users','Players'],['schedule','calendar','Schedule'],['bracket','bracket','Bracket'],['standings','chart','Standings'],['rules','grid','Rules']];q('#tn-detail-view').innerHTML=`<div class="tp-detail-hero">${button('← All tournaments','data-tp-discovery','glass')}<div class="tp-hero-title"><div>${status(t)}<h1>${E(liveMode?'Live Bracket & Schedule':t.name)}</h1><p>${E(liveMode?'Real-time matches, results and court assignments':t.description||'Play. Compete. Belong.')}</p></div><div class="tp-slogan">Play<br><i>Compete</i><br>Belong<span></span></div></div>${facts(t)}${stats(t,d)}</div>${liveMode?`<nav class="tp-live-tabs" aria-label="Live tournament modes">${[['bracket','trophy','Live Bracket'],['schedule','calendar','Match Schedule'],['courts','grid','Court View'],['standings','chart','Standings']].map(([key,ic,name])=>button(icon(ic)+name,`data-tp-tab="${key}" aria-pressed="${tab===key}"`,tab===key?'gold':'glass')).join('')}${button('Event overview','data-tp-tab="overview"','glass')}</nav>`:''}<div class="tp-detail-layout ${liveMode?'tp-live-layout':''}"><main class="tp-main-stack">${liveMode?'':`<nav class="tp-detail-tabs" aria-label="Tournament sections">${tabs.map(([key,ic,name])=>button(icon(ic)+name,`data-tp-tab="${key}" aria-pressed="${tab===key}"`,tab===key?'selected':'plain')).join('')}</nav>`}${!liveMode&&t.registration_open?`<div class="tp-mobile-register">${cta(t)}</div>`:''}<div id="tp-tab-content">${content(d,v)}</div></main>${liveMode?liveOverview(d):registrationPanel(d)}</div>`;tick();requestAnimationFrame(drawConnections);}
  function liveOverview(d){const matches=allMatches(d),live=matches.filter(m=>m.status==='live'),completed=matches.filter(m=>m.status==='completed').length;return `<aside class="tp-live-overview"><h2>${icon('calendar')} Tournament Overview</h2><div class="tp-overview-grid">${[['users',new Set(d.divisions.flatMap(v=>v.teams.flatMap(t=>t.members.map(m=>m.user_id||'g'+m.id)))).size,'Players'],['grid',new Set(live.map(m=>m.court_id).filter(Boolean)).size,'Courts Active'],['trophy',d.divisions.length,'Divisions'],['calendar',matches.filter(m=>!['completed','cancelled'].includes(m.status)).length,'Matches Remaining']].map(([ic,n,txt])=>`<div>${icon(ic)}<b>${n}</b><small>${txt}</small></div>`).join('')}</div>${live[0]?`<section class="tp-featured-match"><h3>${icon('trophy')} Featured Match</h3>${matchCard(live[0])}</section>`:empty('Live scores appear here','Follow the bracket and scheduled matches.')}<h3>Quick Stats</h3><div class="tp-progress-ring" style="--progress:${matches.length?completed/matches.length*100:0}%"><b>${matches.length?Math.round(completed/matches.length*100):0}%</b></div><p>${completed} of ${matches.length} matches completed</p></aside>`;}
  function divisionSelect(d){return `<select data-tp-select-division aria-label="Tournament division">${d.divisions.map(v=>`<option value="${v.id}" ${v.id===Number(divisionId)?'selected':''}>${E(v.name)} · ${E(L(v.match_type))}</option>`).join('')}</select>`;}
  function content(d,v){if(tab==='overview')return `<section class="tp-surface tp-about"><div><h2>About This Tournament</h2><p>${E(d.tournament.description||'Official event information, participants and live results.')}</p><div class="tp-highlights"><span>${icon('pin')}${E(d.tournament.venue||'Venue TBA')}</span><span>${icon('trophy')}${E(d.divisions.map(x=>L(x.match_type)).filter((x,i,a)=>a.indexOf(x)===i).join(' · ')||'Divisions TBA')}</span><span>${icon('users')}Team &amp; player registration</span></div></div><div class="tp-about-photos">${picture(d.tournament.poster_url,d.tournament.name)}${picture(d.courts?.[0]?.image_url)}</div></section><section class="tp-surface"><div class="tp-section-head"><h2>Divisions</h2>${button('View all divisions →','data-tp-tab="divisions"','link')}</div>${divisionsView(d)}</section><section class="tp-surface tp-teams-preview"><div class="tp-section-head"><h2>Teams &amp; Participants</h2>${button('View all players →','data-tp-tab="players"','link')}</div><div class="tp-team-grid">${d.divisions.flatMap(v=>v.teams.slice(0,4).map(t=>teamCard(t,v))).slice(0,4).join('')||empty('Teams appear after registration approval')}</div></section><div class="tp-preview-grid"><section class="tp-surface"><div class="tp-section-head"><h2>${icon('calendar')} Schedule Preview</h2>${button('Full schedule →','data-tp-tab="schedule"','link')}</div>${allMatches(d).slice(0,4).map(m=>`<div class="tp-queue-row"><small>${E(date(m.scheduled_date))} · ${time(m.scheduled_time)}</small><strong>${E(m.team_a?.name||'TBA')} vs ${E(m.team_b?.name||'TBA')}</strong><small>${E(m.court_name||'Court TBA')} · ${E(m.division_name)}</small></div>`).join('')||empty('Schedule to be announced')}</section><section class="tp-surface tp-mini-bracket"><div class="tp-section-head"><h2>${icon('bracket')} Bracket Preview</h2>${button('Full bracket →','data-tp-tab="bracket"','link')}</div>${bracket(v)}</section></div>`;
    if(tab==='divisions')return `<section class="tp-surface"><h2>Tournament Divisions</h2>${divisionsView(d)}</section>`;
    if(tab==='teams')return `<section class="tp-surface"><div class="tp-section-head"><h2>Teams</h2>${divisionSelect(d)}</div><div class="tp-team-grid">${(v?.teams||[]).map(t=>teamCard(t,v)).join('')||empty('No official teams yet')}</div></section>`;
    if(tab==='players')return `<section class="tp-surface"><div class="tp-section-head"><h2>Players</h2>${divisionSelect(d)}</div><div class="tp-player-grid">${(v?.teams||[]).flatMap(t=>t.members.map(p=>`<article class="tp-player-card">${avatar(p,true)}<h3>${E(p.display_name)}</h3><p>${rating(p)}${E(p.player_division||v.name)}</p><div class="tp-chips"><span>${E(t.name)}</span>${t.seed?`<span>Seed ${t.seed}</span>`:''}</div></article>`)).join('')||empty('No official players yet')}</div></section>`;
    if(tab==='rules')return `<section class="tp-surface"><h2>Rules &amp; Format</h2><p>Registration uses the player's official division. Partner eligibility and payment verification are checked by the organiser.</p>${d.divisions.map(v=>`<article class="tp-rule-card"><h3>${E(v.name)} · ${E(L(v.match_type))}</h3><dl><div><dt>Competition format</dt><dd>${E(L(v.competition_format))}</dd></div><div><dt>Seeding</dt><dd>${E(L(v.seeding_method))}</dd></div><div><dt>Match slot / rest</dt><dd>${v.match_duration_minutes} / ${v.rest_minutes} minutes</dd></div><div><dt>Third place match</dt><dd>${v.third_place?'Enabled':'Not enabled'}</dd></div><div><dt>Final reset</dt><dd>${v.competition_format==='double_elimination'?(v.reset_final?'Enabled':'Not enabled'):'Not applicable'}</dd></div></dl>${v.description?`<p>${E(v.description)}</p>`:''}</article>`).join('')}<p class="tp-muted">The scorer records the official match score. Final result confirmation advances the bracket. Game-by-game scoring is not configured in this scoring model.</p></section>`;
    if(tab==='bracket')return `<section class="tp-bracket-surface"><div class="tp-section-head"><div><h2>${E(d.tournament.name)}</h2><small>${E(v?.name||'')} · ${E(L(v?.competition_format))}</small></div>${divisionSelect(d)}</div>${bracket(v)}</section><section class="tp-surface"><div class="tp-section-head"><h2>${icon('calendar')} Match Schedule</h2>${button('View all →','data-tp-tab="schedule"','link')}</div>${schedule(d,4)}</section>`;
    if(tab==='schedule')return `<section class="tp-surface"><div class="tp-section-head"><h2>Match Schedule</h2><select data-tp-select-division aria-label="Division filter"><option value="">All divisions</option>${d.divisions.map(v=>`<option value="${v.id}" ${Number(divisionId)===v.id?'selected':''}>${E(v.name)}</option>`).join('')}</select></div>${schedule(d)}</section>`;
    if(tab==='courts')return `<section class="tp-surface"><h2>Court Operations</h2>${courtView(d)}</section>`;
    return `<section class="tp-surface"><div class="tp-section-head"><h2>Standings</h2>${divisionSelect(d)}</div>${standings(v)}</section>`;
  }
  function findMatch(id){return myMatches.concat(detail?allMatches(detail):[]).find(m=>m.id===Number(id));}
  function calendar(m){if(!m?.scheduled_date||!m.scheduled_time)return;const escapeIcs=v=>String(v||'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const start=m.scheduled_date.replace(/-/g,'')+'T'+m.scheduled_time.replace(/:/g,'').slice(0,4)+'00';const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//PIKOL//Tournament//EN','BEGIN:VEVENT','UID:pikol-match-'+m.id+'@'+location.host,'DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),'DTSTART;TZID='+(ctx?.brand().facility_timezone||'Asia/Manila')+':'+start,'DURATION:PT30M','SUMMARY:'+escapeIcs((m.team_a?.name||m.team_a_name||'TBA')+' vs '+(m.team_b?.name||m.team_b_name||'TBA')),'LOCATION:'+escapeIcs(m.court_name),'DESCRIPTION:'+escapeIcs((m.tournament_name||detail?.tournament.name||'Tournament')+' · '+(m.division_name||'')+' · Check PIKOL for schedule updates.'),'END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/calendar'})),a=document.createElement('a');a.href=url;a.download='PIKOL-match-'+m.id+'.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function handlePlayerClick(e){const b=e.target.closest('button,a');if(!b)return;if(b.hasAttribute('data-tp-nav'))ctx.goto(b.dataset.tpNav);if(b.hasAttribute('data-tp-discovery'))ctx.discovery();if(b.hasAttribute('data-tp-mymatches')){if(detail){ctx.discovery().then(()=>q('#tp-my-matches')?.scrollIntoView({behavior:'smooth'}));}else q('#tp-my-matches')?.scrollIntoView({behavior:'smooth'});}if(b.hasAttribute('data-tp-open'))ctx.open(Number(b.dataset.tpOpen),b.dataset.openTab);if(b.hasAttribute('data-tp-register')){const t=list.find(t=>t.id===Number(b.dataset.tpRegister))||detail?.tournament;ctx.register(Number(b.dataset.tpRegister),t?.name||'Tournament');}if(b.hasAttribute('data-tp-tab')){tab=b.dataset.tpTab;renderDetail();}if(b.hasAttribute('data-tp-division')){divisionId=Number(b.dataset.tpDivision);tab=b.dataset.nextTab||tab;renderDetail();}if(b.hasAttribute('data-tp-calendar'))calendar(findMatch(b.dataset.tpCalendar));if(b.hasAttribute('data-tp-allmatches'))q('.tp-match-grid').innerHTML=myMatches.map(matchCard).join('');if(b.hasAttribute('data-tp-team-edit'))editTeam(Number(b.dataset.tpTeamEdit),ctx,detail);}
  function handleChange(e){const el=e.target;if(el.hasAttribute('data-tp-select-division')){divisionId=el.value?Number(el.value):null;renderDetail();}if(el.hasAttribute('data-tp-filter')){filters[el.dataset.tpFilter]=el.value;renderDetail();}if(el.hasAttribute('data-tp-banner'))uploadBanner(el,ctx,()=>open(detail.tournament.id,ctx,null,true));}
  async function jpeg(file){if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPEG, PNG or WebP image.');if(file.size>12*1024*1024)throw new Error('Choose an image smaller than 12 MB.');const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,1024/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const g=canvas.getContext('2d');g.fillStyle='#082b4f';g.fillRect(0,0,canvas.width,canvas.height);g.drawImage(bitmap,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.84);}finally{bitmap.close();}}
  async function uploadBanner(input,c,refresh){if(!input.files[0])return;input.disabled=true;try{const data_url=await jpeg(input.files[0]);await c.api('/api/tournament-teams/'+input.dataset.tpBanner+'/banner',{method:'POST',body:{data_url}});c.toast('Team banner saved.','success');await refresh();}catch(error){c.toast(error.message,'error');}finally{input.disabled=false;input.value='';}}
  function editTeam(id,c,d){const team=d.divisions.flatMap(v=>v.teams).find(t=>t.id===id);if(!team)return;c.modal({title:'Team identity',confirmText:'Save team name',body:`<label class="label" for="tp-team-name">Team name</label><input class="input" id="tp-team-name" maxlength="120" value="${E(team.name)}">`,onConfirm:async host=>{await c.api('/api/tournament-teams/'+id+'/identity',{method:'PUT',body:{name:q('#tp-team-name',host).value}});if(c===ctx)await open(d.tournament.id,c,null,true);else c.open(d.tournament.id);}});}
  setInterval(()=>{if(document.hidden||!ctx||!detail||q('#tab-tournaments').classList.contains('hidden')||q('.modal-host'))return;open(detail.tournament.id,ctx,null,true);},12000);
  function drawConnections(){
    qa('.tp-bracket-rounds:not(.is-pool)').forEach(board=>{
      board.querySelector('.tp-connectors')?.remove();
      const rect=board.getBoundingClientRect(),ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');
      svg.classList.add('tp-connectors');svg.setAttribute('aria-hidden','true');svg.setAttribute('width',board.scrollWidth);svg.setAttribute('height',board.scrollHeight);
      qa('[data-match-id]',board).forEach(node=>{const next=q('[data-match-id="'+node.dataset.next+'"]',board);if(!next)return;const a=node.getBoundingClientRect(),b=next.getBoundingClientRect(),x1=a.right-rect.left,y1=a.top+a.height/2-rect.top,x2=b.left-rect.left,y2=b.top+b.height/2-rect.top;if(x2<x1)return;const mid=(x1+x2)/2,path=document.createElementNS(ns,'path');path.setAttribute('d','M'+x1+' '+y1+' H'+mid+' V'+y2+' H'+x2);path.setAttribute('fill','none');path.setAttribute('stroke',node.querySelector('.is-winner')?'#55ee91':'#83d7f5');path.setAttribute('stroke-width','1.6');svg.appendChild(path);});board.prepend(svg);
    });
  }
  let connectionResize;window.addEventListener('resize',()=>{clearTimeout(connectionResize);connectionResize=setTimeout(drawConnections,120);});
  root.PikolPremium={drawConnections,load,open,setup,avatar,people,picture,teamCard,memberRow,matchCard,bracket,standings,icon,badge,banner,asset,date,time,label:L,esc:E,jpeg,uploadBanner,editTeam,stats,allMatches,getContext:()=>ctx};
})(window);

(function(root){'use strict';
 const P=root.PikolPremium,q=(s,h)=>h.querySelector(s);
 function step(host,n){host.dataset.premiumStep=String(n);host.querySelectorAll('[data-registration-step]').forEach(el=>el.classList.toggle('tp-step-hidden',Number(el.dataset.registrationStep)!==n));host.querySelectorAll('.tp-steps li').forEach((el,i)=>el.classList.toggle('is-active',i===n-1));const confirm=q('[data-confirm]',host),label=n===1?'Continue to Division →':'Submit & Continue to Payment →';confirm.textContent=label;if(confirm.classList.contains('is-loading'))confirm.dataset.text=label;const back=q('[data-registration-back]',host);if(back)back.classList.toggle('hidden',n===1);}
 function enhance(host,user,info){const dialog=q('.modal',host),fields=q('.registration-fields',host);if(!fields)return;dialog.classList.add('tp-registration-dialog');q('.registration-player',host)?.remove();fields.insertAdjacentHTML('afterbegin',`<ol class="tp-steps"><li><b>1</b>Player / Team</li><li><b>2</b>Division</li><li><b>3</b>Payment</li><li><b>4</b>Confirmation</li></ol><div class="tp-registration-player" data-registration-step="1">${P.avatar(user,true)}<span><strong>${P.esc(user?.full_name||'Player')}</strong><small>${P.esc(info.player_division)} · Official division</small></span></div>`);
  ['#tr-team','#tr-partner-name'].forEach(sel=>{const el=q(sel,host);if(el){const container=sel==='#tr-partner-name'?q('#tr-partner',host):el.closest('.field');container.dataset.registrationStep='1';}});
  ['#tr-division','#tr-notes','#tr-use-credit'].forEach(sel=>{const el=q(sel,host);if(el){let container=el.closest('.field')||el.closest('label')||el.parentElement;container.dataset.registrationStep='2';}});
  q('.info-callout',fields).dataset.registrationStep='2';
  const back=document.createElement('button');back.type='button';back.className='btn btn-outline hidden';back.dataset.registrationBack='';back.textContent='← Player / Team';back.onclick=()=>step(host,1);q('.modal-foot',host).prepend(back);step(host,1);
 }
 function confirmation(modal,r,money){modal({title:'Registration received',body:`<div class="tp-surface"><ol class="tp-steps"><li><b>✓</b>Player / Team</li><li><b>✓</b>Division</li><li><b>✓</b>Payment</li><li class="is-active"><b>4</b>Confirmation</li></ol><h2>You're registered</h2><p>Registration #${P.esc(r.registration.id)} is pending organiser approval.</p><p>Payment status: ${P.esc(P.label(r.registration.payment_status))}</p><p>PIKOL Credit used: ${money(r.credit_used)}</p><p>Follow the status in My Registrations.</p></div>`});}
 root.PikolPremiumRegistration={step,enhance,confirmation};
})(window);
