/* Admin tournament content. Native navigation, dialogs and business handlers remain authoritative. */
(function(root){'use strict';
 const P=root.PikolPremium,E=P.esc,q=(s,h=document)=>h.querySelector(s);let context=null,data=null,currentFilter='all',request=0,detail=null,selectedDivisionId=null,activeTab='overview';
 const btn=(t,a='',kind='outline')=>`<button type="button" class="tp-btn tp-${kind}" ${a}>${t}</button>`;
 function mount(){let host=q('#tp-command');if(host)return host;host=document.createElement('div');host.id='tp-command';host.className='tp-command';const list=q('#trn-list-view'),table=q('#tournaments-body').closest('.table-wrap');table.replaceWith(host);host.addEventListener('click',handle);P.bindCards(host);return host;}
 async function load(c){context=c;const n=++request,host=mount();host.innerHTML='<div class="tp-empty" role="status">Loading tournaments…</div>';try{const summary=await c.api('/api/admin/tournaments-summary');if(n!==request)return;data=summary;render();}catch(error){host.innerHTML=`<div class="tp-surface"><h2>Tournaments could not load</h2><p>${E(error.message)}</p>${btn('Retry','data-command-retry')}</div>`;}}
 function tournamentCard(t){return `<article class="tp-admin-tournament" role="link" tabindex="0" data-card-nav data-trn-open="${t.id}" aria-label="Open ${E(t.name)}">${P.picture(t.poster_url,t.name)}<div><h3>${E(t.name)}</h3>${P.badge(t.status)}<p class="tp-event-meta">${P.date(t.tournament_date)} · ${E(t.venue||'Venue TBA')}</p><div class="tp-chips"><span>${t.division_count||data.divisions.filter(d=>d.tournament_id===t.id).length} divisions</span><span>${t.player_count||0} players</span><span>${t.live_count||0} live matches</span></div></div></article>`;}
 function render(){const s=data.stats,rows=data.tournaments.filter(t=>currentFilter==='all'||currentFilter==='upcoming'&&!['live','completed','cancelled','draft'].includes(t.status)||t.status===currentFilter);mount().innerHTML=`<div class="tp-command-stats">${[[s.active,'Active Tournaments','trophy'],[s.pending,'Pending Approvals','users'],[s.live,'Live Matches','live'],[s.occupied+' / '+s.courts,'Courts Occupied','grid']].map(([n,t,ic])=>`<div class="tp-command-stat">${P.icon(ic)}<span><b>${E(n)}</b><small>${t}</small></span></div>`).join('')}</div><div class="tp-command-layout"><section class="tp-surface"><h2>Tournaments</h2><div class="tp-command-filters">${['all','upcoming','live','completed'].map(v=>btn(P.label(v),`data-command-filter="${v}" aria-pressed="${v===currentFilter}"`,v===currentFilter?'blue':'outline')).join('')}</div>${rows.map(tournamentCard).join('')||'<div class="tp-empty">No tournaments in this view.</div>'}</section><section class="tp-surface"><h2>Registration Review</h2><p class="tp-muted">Use the registration list below to review player details and payments before approval.</p>${btn('Open approval queue','data-command-regs')}${btn('Manage scorer accounts','data-command-staff')}</section></div>`;}
 function handle(e){const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-command-retry'))load(context);if(b.hasAttribute('data-command-filter')){currentFilter=b.dataset.commandFilter;render();}if(b.hasAttribute('data-command-regs'))q('#treg-status').scrollIntoView({behavior:'smooth',block:'center'});if(b.hasAttribute('data-command-staff'))context.scorers();}
 function enhanceDetail(host,d,c){context=c;P.setAdminContext(c);detail=d;if(String(host.dataset.tournamentId)!==String(d.tournament.id)){selectedDivisionId=d.divisions[0]?.id;activeTab='overview';host.dataset.tournamentId=d.tournament.id;}if(!d.divisions.some(v=>String(v.id)===String(selectedDivisionId)))selectedDivisionId=d.divisions[0]?.id;const target=q('#tp-admin-workspace',host);target.innerHTML=P.workspace(d,selectedDivisionId,activeTab,true);if(!host.dataset.workspaceBound){host.dataset.workspaceBound='1';P.bindCards(host);host.addEventListener('change',e=>{if(e.target.matches('[data-tp-select-division]')){selectedDivisionId=Number(e.target.value);update();q('[data-tp-select-division]',host).focus({preventScroll:true});}});host.addEventListener('click',e=>{let b=e.target.closest('button,a');const card=e.target.closest('[data-card-nav]');if(card&&!b)b=card;if(!b)return;if(b.hasAttribute('data-tp-tab')){activeTab=b.dataset.tpTab;update();q('[data-tp-tab="'+activeTab+'"]',host).focus({preventScroll:true});}if(b.hasAttribute('data-tp-identity'))P.identity(detail,context,true);if(b.hasAttribute('data-tp-team'))P.identity(detail,context,true,b.dataset.tpTeam);if(b.hasAttribute('data-tp-match'))P.matchDetail(P.allMatches(detail).find(m=>String(m.id)===b.dataset.tpMatch),context,true);if(b.hasAttribute('data-tp-print'))P.printDivision(detail,detail.divisions.find(v=>String(v.id)===b.dataset.tpPrint),context);});}requestAnimationFrame(P.drawConnections);}
 function update(){q('#tp-admin-workspace').innerHTML=P.workspace(detail,selectedDivisionId,activeTab,true);requestAnimationFrame(P.drawConnections);}
 root.PikolTournamentCommand={load,enhanceDetail,selectedDivision:()=>selectedDivisionId};
})(window);
